### ISSUE TITLE
Add Send/Receive Picons from FTP transfer window

### ISSUE THREAD

**Issue by mapi68** [DYefremov/DemonEditor#101]
This is an example what I mean.....

![screenshot_2022_04_28_at_07_47_20](https://user-images.githubusercontent.com/41143572/165686928-a3c75fa3-c354-444f-91e9-cf39b9e0ef2d.png)

**Comment by DYefremov** [comment]
Yes, there are no problems with this. I can add it. But the Send/Receive buttons on the 'Picons' tab play another role also. You can drag a picon from the explorer to the desired button and, depending on the button, the piсon will be uploaded or downloaded. 
I plan to do some refactoring. And perhaps this dialog will not exist at all. There will be buttons common to all tabs on the toolbar next to the profile selection. And depending on the tab, the necessary data will be loaded. But I haven't decided yet... :) There may be other options...

**Comment by DYefremov** [comment]
Approximately as in this program. 

![e2toolkit](https://user-images.githubusercontent.com/7511379/165725705-95185575-245e-4287-bb5c-9b6e2a716add.png)

This is another  [project ](https://github.com/DYefremov/E2Toolkit)from me.

**Comment by DYefremov** [comment]
At the moment i have added your variant. I hope it will be helpful.

![picons](https://user-images.githubusercontent.com/7511379/166008187-fbca76d5-e721-4e63-964b-da775498646e.png)

**Comment by mapi68** [comment]
It works for Picons only if it's selected "Picons", but with "All" only take Bouquets + Satellites.
Isn't it better remove radio buttons and put check?

![check](https://user-images.githubusercontent.com/41143572/166090096-adef2ed7-c3d9-4cff-bf39-5c845fc4d35d.png)

**Comment by DYefremov** [comment]
> It works for Picons only if it's selected "Picons", but with "All" only take Bouquets + Satellites.

Yes, that's how it was meant to be.

> Isn't it better remove radio buttons and put check?

Yes, this is also a working option. The main question is what is more convenient. Need to experiment.

This option also needs to be considered.

> There will be buttons common to all tabs on the toolbar next to the profile selection. More or less like this:
> 
> ![buttons](https://user-images.githubusercontent.com/7511379/165730425-b2153168-e444-4e2a-a1fa-5385a9062cdc.png)

 I think that would be even more convenient. But this is just a guess. Users may think differently.

**Comment by mapi68** [comment]
For me it will be beautilful with buttons common to all tabs on the toolbar next to the profile selection.

Please consider to add in Settings ---> Program "Compress PIcons before send to receiver"
You the Best

**Comment by DYefremov** [comment]
> For me it will be beautilful with buttons common to all tabs on the toolbar next to the profile selection.

Ok. For now, let's stick with this option. But this will require significant changes in the app. In any case, I've already planned something similar. :)

> Please consider to add in Settings ---> Program ---> "Compress PIcons before send to receiver"

I don’t see any big problems here, but I need an exact understanding of what is meant by:

> Compress PIcons

it is not entirely clear what or how compression should occur.

**Comment by mapi68** [comment]
>> Compress PIcons

> It is not entirely clear what or how compression should occur.

If you have 2 or more satellites it's normal to have more than 5000 picons and transfer with FTP may will be slow. 
To speedup the process DE can compress ALL PICONS with 7z or tar.gz, send the archive to receiver in /tmp/ and after unzip it to picons folder of receiver.

**Comment by DYefremov** [comment]
Unfortunately, this doesn't make much sense.
1. Just compress one *.png file and compare the size before and after.
2. Add time to compress and then decompress. If this is a modern receiver, it may not be so critical.
3. How do you plan to unpack and then move (what commands, plugins, scripts) files?

**Comment by mapi68** [comment]
> Unfortunately, this doesn't make much sense.

dreamboxEDIT make this
> How do you plan to unpack and then move (what commands, plugins, scripts) files?

**This is the log of dreamboxEDIT** 
Compressing Picons
** Sending file "/tmp/picon.zip" **
FTP-Transfer wird gestartet
Transfer abgeschlossen
Verbindung wird getrennt.
Verbindung getrennt.
Sending Reload commands.
Reload of lamedb and userbouquets succeded.
Reload of satellites.xml succeded.
Reload of blacklist succeded.
Telnet status: Host-Name dm900 wird aufgelöst.
Telnet status: Verbinden mit 192.168.1.20.
Telnet status: Verbunden.
Sending username root
Sending password ********
Sending username root
Extracting Picons
Picons successfully extracted
Terminating telnet
Telnet status: Verbindung getrennt.

**Comment by DYefremov** [comment]
Yes I know that. :) Telnet option. But I refused this opportunity at the design stage. Unfortunately I don't remember why. Perhaps there were problems with unpacking (for Boxes  with a small amount of memory. As I already wrote, for modern receivers, apparently no longer relevant) or with the library used for telnet. Of course, nothing prevents us from trying again, as an option in the form of an experimental feature that is separately enabled by the user.

**Comment by mapi68** [comment]
Yes, problems with unpacking for low memory decoder.
But if you have in Settings ---> Program ---> "Compress PIcons before send to receiver" disabled you send picons one by one and don't have this problem.

**Comment by DYefremov** [comment]
Ok.
> nothing prevents us from trying again

We can experiment.:) But by default, this option should be disabled.

**Comment by DYefremov** [comment]
I have added automatic picon compression during upload if the selected picon count > 1000. 
![picons](https://user-images.githubusercontent.com/7511379/166704718-f979aee6-9283-4121-b8cb-cc0797c09a78.png)

I think this would be a compromise option.

**Comment by mapi68** [comment]
Yes, but for oldest receiver with low memory it's better to add a check of picons.zip size if is greater than free space in /tmp/

**Comment by DYefremov** [comment]
Added option to settings:
![settings](https://user-images.githubusercontent.com/7511379/166817569-65060211-039b-4859-9fb9-3a7b7f0742a5.png)

**Comment by mapi68** [comment]
Works good with compression and transfer to receiver, but after when receiver with telnet extract, it stops after transfer 100-200 picon of 4000 and remove picons.zip
Maybe telnet timeout problem?
Tried to change  up timeout of telnet in connections.py and extract more icons.

**Comment by DYefremov** [comment]
My mistake. Test again!
