### ISSUE TITLE
Issue FTP selection

### ISSUE THREAD

**Issue by i-mirror** [DYefremov/DemonEditor#106]
In FTP, when making a multiple selection, clicking with the right mouse button deactivates the multiple selection.

![Screenshot_20220516_202101](https://user-images.githubusercontent.com/7964751/168657562-ae7d7413-2f7f-4ff6-9403-a621df057454.png)

**Comment by DYefremov** [comment]
This is the default behavior (for the used GTK+ library). For the services and the bouquet lists  this behavior is overridden.

**Comment by i-mirror** [comment]
OK, thanks.
