### ISSUE TITLE
Some minor improvements

### ISSUE THREAD

**Issue by kybos** [DYefremov/DemonEditor#110]
Thanks for this editor, I've just discovered it, but it seems quite a comprehensive and mature piece of software, very nice. So far working smoothly with my VU+.

Some suggestions that would help my workflow:
1. Timer tab: Make the columns resizable.
2. New timer: When the start time is set, set the end time automatically to the same value (or the same value + 60 minutes or so), but of course only if end time < start time. This would help to avoid several clicks/inputs each time in a typical creation of a new timer.
3. The VU+ has a Deep Standby mode (which I normally use when switching off). Not sure if it belongs to the enigma2 standard so it could be implemented here as well.

Thanks.

**Comment by DYefremov** [comment]
Hi, 
For point 
1.  No problem. Done.
2. Did it partially. Made the default timer end value 1 hour more than the start value.
> but of course only if end time < start time

This is checked by the enigma itself before adding the timer. We can add additional check in the program itself, but I need to think about how to do it more correctly and conveniently for the user. So far, this is not a priority. We'll see later.

3. If I understood correctly, then it is already on board:
![power](https://user-images.githubusercontent.com/7511379/177702141-da4877d1-cc3c-4e26-aec7-a8da0f016906.png)

**Comment by kybos** [comment]
1. Thanks.

2. Sorry, my explanation was unclear. I did mean adding extra checks when the timer is saved (=added/sent to the receiver). As you say, a check is done by enigma anyway.
But when I create a new timer and edit the values in the timer popup in the program itself: 
    - I edit the start timestamp in the corresponding date/time popup. 
    - When finished, I click Set to save the timestamp and get back to the timer popup. At this moment (clicking Set) also the end timestamp should be adjusted dynamically, i.e. set to the start time + 1 hour (but only if the end timestamp is  lower than the start timestamp at this moment, to avoid unwanted changes to existing timers when editing them later).

    I think that would be a great usability improvement, saving lots of unnecessary clicks when editing the end timestamp, having to set the values for month, day and/or the hour manually again, although it's obvious that they are the same as in the start timestamp.

3. Yes, you are probably right, Shutdown seems to be the same function as Deep Standby in VU+, it's just different terminology.

**Comment by DYefremov** [comment]
Yes, I think the behavior for point 2 is quite working. I will try to implement as possible.

**Comment by DYefremov** [comment]
I made changes to the timer setting. Hope it will be really helpful. If I missed something let me know!

**Comment by kybos** [comment]
Very nice, thanks! When you create a lot of timers at the same time, this is a huge efficiency improvement!

Some cosmetic details I've just noticed - about the inconsistent formatting of the timestamp string:

![image](https://user-images.githubusercontent.com/10009541/178046328-7156d93c-2f8f-42cf-9e3e-3a19adfb9d8d.png)

![image](https://user-images.githubusercontent.com/10009541/178047096-fe2b7df4-8b7c-49fc-9865-82ae72fff827.png)

And also the Time display in the list: The weekday display is not so helpful if you have a lot of timers. The date would be better IMHO:

![image](https://user-images.githubusercontent.com/10009541/178048016-2cd3c273-d304-4999-924d-f2f2d0cc2555.png)

**Comment by DYefremov** [comment]
> inconsistent formatting

Corrected!

> The date would be better

I personally like the day of the week better, but I'll think...

P.S. As far as I can understand, you actively use timers. I recommend paying the same attention to the EPG tab. Perhaps you already know. Here you can select (filter) several events at once and create the required number of timers in one click. In addition, on the Timers tab, you can drag and drop services from the favorites list onto the list of timers...

**Comment by kybos** [comment]
Thanks, the drag&drop feature for the timers is really practical.

As for EPG: Sure, it can be comfortable for events not so far in the future. Playing around, I noticed several issues:
1. Again, there is weekday instead of date, so orientation in the list is difficult. 
2. It seems that only the first line of the program description is displayed, even if more is available in EPG.
3. Currently the columns are not resizable, and even if the description is cut off, no scrollbars are displayed.

**Comment by DYefremov** [comment]
> 1. there is weekday instead of date, so orientation in the list is difficult.

Yes, you may be right. I will experiment as much as possible.

**Comment by kybos** [comment]
> > 2. It seems that only the first line of the program description is displayed, even if more is available in EPG.
> 
> If I understand correctly, the tooltip should help. Just hover your mouse over the desired line.

No, the tooltip just displays the available description. But the description ifself is not complete (compared with the same EPG text on the receiver/TV or in OpenWebif). It seems that the description is always cut off after the first line break. This is especially noticeable when the first line of the original EPG text is empty (=it starts on the second line), which is often the case - then there is no description at all displayed in the DemonEditor.

I also noticed that for events with empty description no timer can be created from the EPG pane.

Apart from these issues, the ideal scenario for my purpose would be something like this:
- Download/Update the EPG info for all programs in a bouquet.
- Full text search over the EPG text for the whole bouquet.
- Display the search results in the EPG pane, including the full EPG text descriptions, so I can check it and decide for which I want to create timers.

But I can imagine that would be quite a lot of work, and possibly not in line with your intentions for the EPG functionality...

**Comment by DYefremov** [comment]
> the first line of the original EPG text is empty (=it starts on the second line), which is often the case - then there is no description at all displayed in

Unfortunately I can't reproduce it on my channel list (I'm using the openATV 7.0 image). In any case, at the moment it is not so important.

> But I can imagine that would be quite a lot of work, and possibly not in line with your intentions for the EPG functionality...

In the current version, it is planned to focus on getting EPG from sources other than the receiver's WEB API (e.g XMLTV). But... The option that you need is technically not so difficult to implement, for example, using the same WEB API of the receiver. Approximate analogue of MultiEPG in Webif. For example, add a separate tab like on the bouquets tab (DVB-IPTV) and populating with data when choosing a bouquet.  At least, I'll add this feature to my wishlist :)

**Comment by DYefremov** [comment]
Played a little with the time display for the Timers and EPG tabs. Perhaps this variant will be a compromise?
![time](https://user-images.githubusercontent.com/7511379/178138767-15df4a63-debe-453e-8e5c-b2f18f3d26e7.png)

**Comment by kybos** [comment]
Yes, that would make the events identifiable. But it does not solve the problem with the (chronological) sorting - if I see it right, the time column is sorted alphabetically (so it even depends on your current language).
Would putting the date first, then weekday, be an option? Then the sorting would work as well.
BTW: It affects also the Recordings tab.

**Comment by DYefremov** [comment]
> Would putting the date first, then weekday, be an option?

Unfortunately this won't help. To implement this logic, it is necessary to somewhat complicate work on cell data rendering. When I have time, I will try to experiment.

**Comment by DYefremov** [comment]
I have changed the sort order for the time column. For EPG tab only. Just for experiment. Besides made columns resizable.

**Comment by kybos** [comment]
Yes, that works well!

**Comment by kybos** [comment]
Now that the timestamp sorting works independently of the string representation, I would suggest to output the date in a region-specific format, depending on the system locale. I am new to python, but this seems to be very easy: Just replace the hard-coded format string like %Y-%m-%d by %x in the timestamp functions.

E.g. in most of Middle Europe the usual date format is like this, which works perfectly with %x (I also replaced %A by %a for the abbreviated weekday in my testing, because the weekday names are just too long and they waste too much space):

![image](https://user-images.githubusercontent.com/10009541/178569738-5c16d0cd-4922-4cd2-90df-c79e949acc69.png)

I noticed some more inconsistencies:
On the FTP tab, FTP side, the timestamps look quite weird (mix of year and time in the second part):

![image](https://user-images.githubusercontent.com/10009541/178570853-014edf10-b16f-469b-8d08-53b03756c212.png)

On the PC pane it looks ok, but the date format is again different than on the other tabs.

I also noticed that the Settings->Network tab is not functional ATM in the 3.0 alpha (not possible to change the receiver IP or change/create profiles, close button must be clicked twice to close the popup etc.). But I suppose it's because you are working at it, and know about it.

**Comment by DYefremov** [comment]
> Just replace the hard-coded format string like %Y-%m-%d by %x in the timestamp functions

I am aware of this option, but this format depends on the current locale. I wanted to avoid this. :)

> I also replaced %A by %a

Yes, this option is ok. I think we can use it.

> On the PC pane it looks ok, but the date format is again different than on the other tabs.

We get this option already in this form when parsing the file line using ftplib . Additional conversion and processing seems redundant to me.

> not possible to change the receiver IP or change/create profiles, close button must be clicked twice to close the popup etc.

This is VERY interesting. I can't reproduce this at me. What OS (Distro) are you using? Something similar was in the old distributions based on Ubuntu 18.04.

**Comment by kybos** [comment]
> > not possible to change the receiver IP or change/create profiles, close button must be clicked twice to close the popup etc.
> 
> This is VERY interesting. I can't reproduce this at me. What OS (Distro) are you using? Something similar was in the old distributions based on Ubuntu 18.04.

Right, I use Mint 19.3, based on Ubuntu 18.04. Still supported (till April 30, 2023).
If the issue really only occurs in this specific version, then don't bother fixing it. In the official beta version it's working, so I can make necessary changes there.

> > Just replace the hard-coded format string like %Y-%m-%d by %x in the timestamp functions
> 
> I am aware of this option, but this format depends on the current locale. I wanted to avoid this. :)

For what reason, if I may ask? I think that's what users expect. In some countries the familiar date formats can be quite special (with swapped month/day etc.).

**Comment by DYefremov** [comment]
> In any case, it is desirable to fix it.

Did a little trick. Should help.

**Comment by kybos** [comment]
> Did a little trick. Should help.

Yes, it works fine now, thanks.

> As my own practice shows, this is not always true. User requests are sometimes very unpredictable. In any case, nothing prevents us from changing the current format as experiment and waiting for feedback. :)

You are certainly right about that, each user has his/her own expectations, which can go from unpredictable to irrational...

But in the case of date/time format, I believe that's a little different. It's part of the design of every OS (or Desktop in Linux) that there exists a global setting for exactly that (usually under Languages or Regional settings or similar), which all programs should stick to (using the locale-specific formatting for date), to achieve consistent UX. If a user is not happy with the date display, the obvious way is to change the corresponding setting in the OS. In most cases it can be set independently of the system language.

**Comment by DYefremov** [comment]
Yes. Theoretically, you are right, but ... The truth of life is that the user is often not interested (or rather not interested at all) in the consistency of the UX. A lot of users don't even know possibilities for locale settings and the like. In general, this is a very extensive and separate topic, what is the correct user interface. Even very large companies very conditionally follow the rules that they themselves came up with. After all, it is far from a fact that what you have developed is really convenient from the user's point of view. How to define it? Who said that swiping down when using a smartphone is to close a window, not to open something. And who even said that gestures is are right? The user is simply accustomed to many things! Okay, I think we can finish this topic. In any case, we are free in our choice. I think we can safely change the format. :)

**Comment by DYefremov** [comment]
I have changed the format. In addition, for the EPG tab, extended description should be shown as a tooltip if present. Unfortunately I can't test it. Hope it works.

**Comment by kybos** [comment]
Yes, it works, thanks.
