### ISSUE TITLE
browsing speed

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#115]
first downloading bouquet from STB, movement in channels list are very slow, this will gone once you save bouquet to (PC) and opening again

- might program save bouquet to PC and opened automatic after downloading from stb? (folder name - date+time?)

**Comment by DYefremov** [comment]
> first downloading bouquet from STB, movement in channels list are very slow, this will gone once you save bouquet to (PC) and opening again

Possibly related to the OS used and library versions. Need to test. What OS version are you using?

> * might program save bouquet to PC and opened automatic after downloading from stb? (folder name - date+time?)

It's not entirely clear what you mean.

**Comment by luxorko** [comment]
- OS -Win 10

**Comment by DYefremov** [comment]
Please test with [this version](https://github.com/DYefremov/DemonEditor/releases/tag/3.0.0-a2).

**Comment by luxorko** [comment]
without any lag.smooth movement in all menu , excellent work thank you

**Comment by DYefremov** [comment]
Ok. We can close.
