### ISSUE TITLE
Picons assign

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#117]
option picon - when click on channel, channel name should by automatic showing in "filter" and showing all availables picons

filtering - if channel name is (205_Boomerang) ; nothing find becouse he looking for whole channel name , but when just wrote "boomerang" channels find it. could be improve filter - filtering? 

In Picon card (right on picture - could you add "sat. possition + provider+ frequence) - this will really help to choosing right picon for iptv channel  

when assign picons - picon references should be transfer as well for channel as well. otherwise all channels with same reference get same picon.
 
<img width="644" alt="Capture" src="https://user-images.githubusercontent.com/65136999/185784189-ecc94935-36c0-4a8a-9c68-e8c68553cf45.PNG">

**Comment by DYefremov** [comment]
Hi,
> option picon - when click on channel, channel name should by automatic showing in "filter" and showing all availables picons

The "auto" switch must be enabled.

> when assign picons - picon references should be transfer as well for channel as well. otherwise all channels with same reference get same picon.

If the channels have the same link, then it is the same channel for Enigma2! 

> In Picon card (right on picture - could you add "sat. possition + provider+ frequence) - this will really help to choosing right picon for iptv channel

![picons](https://user-images.githubusercontent.com/7511379/185807902-8ee41ef5-da0c-4d41-8358-15325be19151.png)

> filtering - if channel name is (205_Boomerang) ; nothing find becouse he looking for whole channel name , but when just wrote "boomerang" channels find it. could be improve filter - filtering?

I can't reproduce it. Needs to test.

**Comment by luxorko** [comment]
The "auto" switch must be enabled. - picons not found it 
![Capture1](https://user-images.githubusercontent.com/65136999/185813088-807622dc-1fc9-4ae7-a7b7-5bc07603ae64.PNG)

If the channels have the same link, then it is the same channel for Enigma2

ALL IPTV channels have same basic reference
 
![Capture3](https://user-images.githubusercontent.com/65136999/185813145-bb0f9eb6-ba82-4194-9743-746773907583.PNG)

could you make could be possible - during assign picons to iptv channel will be "change - rewrite " picon reference to iptv channel??

**Comment by DYefremov** [comment]
> during assign picons to iptv channel will be "change - rewrite " picon reference to iptv channe

Everything you need is already on board. You can configure the IPTV list when importing into a bouquet, or after (IPTV menu -> List configuration). 

![import](https://user-images.githubusercontent.com/7511379/185845791-b6e21acc-19fb-4209-9b4c-3f30db5585b2.png)

> ALL IPTV channels have same basic reference

See above.

**Comment by luxorko** [comment]
> Everything you need is already on board.
sorry, in win 10 looks diference..
![Capture](https://user-images.githubusercontent.com/65136999/185859600-1b48484d-266c-4e5f-a21e-a93fdc2db68c.PNG)

scenario:
- we have IPTV list for" Germany channels". we know this channels are on "Astra 19.2"  
picon card will download all picons from 19.2
![Capture](https://user-images.githubusercontent.com/65136999/185860764-83a999dd-fe93-4311-86ca-6eb03ea1b5af.PNG)

- than go to picon card "explorer card" and choose right picon for IPTV channel (Boomerang) 
the card "explorer" should have more column (sat.possition + provider + freq) -helping to choosing right picon
![Capture1](https://user-images.githubusercontent.com/65136999/185861524-8125edfc-2112-4b4c-8c32-0c6c386f1d1d.PNG)

- now just double click on picon and prog."demoneditor" will ask "would you like to assign picon for (channels name) with reference?" 
click yes and job done. 
nice and easy
could by possible? what do you think?

l

**Comment by DYefremov** [comment]
> sorry, in win 10 looks diference

My dialog screenshot is for m3u import.

> * now just double click on picon and prog."demoneditor" will ask "would you like to assign picon for (channels name) with reference?"

You can select several channels in the bouquet and drag the piсon from the explorer to the selected services in the bouquet! Try it!

> * the card "explorer" should have more column (sat.possition + provider + freq) -helping to choosing right picon

I think it can be made. For example like here:
![picons](https://user-images.githubusercontent.com/7511379/186003838-bf648a6d-274d-414a-bfe9-07256817f36f.png)

Or with additional column with extra info.

**Comment by luxorko** [comment]
> You can select several channels in the bouquet and [drag](url) the piсon from the explorer to the selected services in the bouquet!

**Comment by luxorko** [comment]
> filtering - if channel name is (205_Boomerang) ; nothing find becouse he looking for whole channel name , but when just wrote "boomerang" channels find it. could be improve filter - filtering?
> 
 could you update please

**Comment by luxorko** [comment]
> > filtering - if channel name is (205_Boomerang) ; nothing find becouse he looking for whole channel name , but when just wrote "boomerang" channels find it. could be improve filter - filtering?
> 
> I can't reproduce it. Needs to test.

in "filter " just add some number before channel name :)

**Comment by DYefremov** [comment]
> I can't reproduce it. Needs to test.

![picons_filter](https://user-images.githubusercontent.com/7511379/186021228-db2d2cd0-f618-4387-9ae4-19d631524f1e.PNG)

**Comment by DYefremov** [comment]
> in "filter " just add some number before channel name

Then it's your fault. Are you looking for 'google' or '1google'?

**Comment by DYefremov** [comment]
> yes is work but problem are reference...all IPTV in bouquet have same reference

> can configure the IPTV list when importing into a bouquet, or after (IPTV menu -> List configuration).
