### ISSUE TITLE
epg assign

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#118]
epg for iptv - "Filter + Auto" should by activated straight away
 filtering problem - searching full channel name  "205_Boomerang" nothing find - need delet  "205_" and achannels find it -
 could you improve filter-filterring please

**Comment by DYefremov** [comment]
Similar to the [question with picons](https://github.com/DYefremov/DemonEditor/issues/117). Needs testing. I'll take a look if possible.

**Comment by DYefremov** [comment]
Closed due to duplication of task.
