### ISSUE TITLE
ftp setting 

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#120]
cannot find "FTP Setting" were present in 2.4.4 
missing option Yes-No = remove unused bouquets
![Capture](https://user-images.githubusercontent.com/65136999/186209342-00d68496-3b41-44e1-af41-2ba28272df6f.PNG)

**Comment by DYefremov** [comment]
In settings:
![ftp_settingd](https://user-images.githubusercontent.com/7511379/186225315-fbd75a6e-1729-4c36-9291-ff5535ec76ff.png)

**Comment by luxorko** [comment]
thank you,
realy like this program
