### ISSUE TITLE
saving folder

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#121]
- downloading bouquet from STB to program
- make some changed and bouquet save as to folder "23.08"
- opening program demon - opening buquets from folder "23.08"
- do same change and press " SAVE" in File 

except to be save it there, where get opening from, BUT saving do not save in folder 23.08
all get save to path on picture
![1](https://user-images.githubusercontent.com/65136999/186229591-d7d37666-c0eb-4c30-8c0e-8350fd5f385d.PNG)

**Comment by luxorko** [comment]
no much user friendlly. Thank you letting us know. 
ill close this now

**Comment by DYefremov** [comment]
Perhaps not usual, but quite justified. For example, you do not change the external source data (keep it intact). If you really need to change the given source, just use "Save As".  It's more a matter of preference... :)
