### ISSUE TITLE
filter result

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#122]
have fiter word " RTL" and result are bit stange, why no by alphabet? ... see picture  

![1](https://user-images.githubusercontent.com/65136999/186232578-eaa41c1a-1e5f-444c-9143-6f54de786ff2.PNG)

filtering i mensioned before (picon; EPG...)
any change for upgade, please

**Comment by DYefremov** [comment]
> why no by alphabet?

Because it is a sorting function and not a filtering function. The gas pedal is not for slow down either.

**Comment by luxorko** [comment]
im just user,...thank for explain.
now is closed

**Comment by DYefremov** [comment]
You should understand that when filtering the data you expect to get some set. But it is not at all obvious that users also need to sort this data. For example, it is not clear to sort by which column, in what order, etc. In addition, sorting at the time of filtering will also slow down the process of filtering itself. Sometimes very significant. I think this is not wat users need.
