### ISSUE TITLE
Setting paths in Windows.

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#123]
change patch - choosing folder - save - asking choose folder - save - cyckling question
only close program help keep patch
![2](https://user-images.githubusercontent.com/65136999/186769425-84b97acb-5a8d-47ea-a34f-c76b1893b777.JPG)

file - opening -going to (see picture) = should search folder by "patch"    
![1](https://user-images.githubusercontent.com/65136999/186769682-6202f0eb-b6f5-4db2-80a3-584da818873a.jpg)

**Comment by DYefremov** [comment]
Unfortunately, I can't reproduce it. Works on all my OSes. Please specify your System. OS -> Version -> Language  - etc. I'll try to test it in a virtual machine.

**Comment by luxorko** [comment]
win 10 home - eng

**Comment by luxorko** [comment]
problem remain in  3.0.0 beta

**Comment by DYefremov** [comment]
This problem has not yet been resolved. Perhaps it is related to the peculiarities of the work or the bug in the graphic library on Windows. I found a solution to this problem, but it requires changing the widget type (for example, as in the 'Picons' -> 'Converter' tab), which will also affect other systems, which I don't want yet. Although the option is quite working. I'm just not completely sure that it will fit in this case.

**Comment by luxorko** [comment]
Although the option is quite working. I'm just not completely sure that it will fit in this case.

i could test for you

**Comment by DYefremov** [comment]
Please test [this version](https://github.com/DYefremov/DemonEditor/releases/tag/3.1.0-a1)!

**Comment by DYefremov** [comment]
https://github.com/DYefremov/DemonEditor/issues/130#issuecomment-1312592010
