### ISSUE TITLE
service dvb search

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#126]
1- when searching word "cinema" -  find it first channel with word "cinema" in the name -
 better will be if on first possition will be showing all channels beginning with word "cinema" and then will be showing channels where word "cinema" on the other possition in channel name

2 - please see same picture - in column service - channels name get cutting name early even space there "150 SuperNova Trze...."

![pic1](https://user-images.githubusercontent.com/65136999/193866559-1c6a2d4c-fe20-4a5b-aada-991d8ed79519.JPG)

regarding 2 report = this problem not exist when you go to card IPTV see picture

![Ca1](https://user-images.githubusercontent.com/65136999/193872756-4862ec3b-1d73-464e-8bb6-ef76e0d82287.JPG)

**Comment by DYefremov** [comment]
p. 1. I don't think that's a good idea. Since additional data processing is required (sorting + moving). This can significantly slow down the search.
With regards to the p. 2. Ill test what you mean. But I think, it should be all ok here. I'll test.

**Comment by luxorko** [comment]
With regards to the p. 2. Ill test what you mean. But I think, it should be all ok here. I'll test.

version 3.1.0 still problem with shrinking "channel name in DVB bouquet

![Capture7](https://user-images.githubusercontent.com/65136999/201498408-d40920cd-c6ba-4073-9635-2bd67860088b.JPG)

**Comment by DYefremov** [comment]
Thanks to your screenshot, I finally understand what you mean. :) The ''Service'' column has a limit on the number of displayed characters  (< 25). In the next version I will try to increase this value or even remove the limit.

**Comment by luxorko** [comment]
in the "Service" column showing full channel name. great job.

Could by also possible to make "reverse" please - channels name are srink - cutting name early please see attached pictute
channel name "Eleven Sports Pro League 1 NL" - only two character "NL" missing - should be vissible without srink namw 

![Capture](https://user-images.githubusercontent.com/65136999/205991144-b0555dcb-4960-4a7c-83a8-ee147b5ec3dc.JPG)

**Comment by DYefremov** [comment]
> lots af space in culumn avaiable

Since this place can be used for other things.

![services_column](https://user-images.githubusercontent.com/7511379/206026707-ba145ee8-72fe-42b0-ad58-6e4852a92954.png)
