### ISSUE TITLE
iptv card not showing picon

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#131]
iptv card not showing picons, reference there and match; picon downloaded demon, 

import to stb (picon+iptv bouquet)  picons correctlly showing on TV screen 

![iptv picon](https://user-images.githubusercontent.com/65136999/195980840-e34ad91a-c4b9-414d-bb38-b8c75fca309c.JPG)

**Comment by DYefremov** [comment]
How can I reproduce it?

![picon_iptv](https://user-images.githubusercontent.com/7511379/195996482-2a4d985c-638d-42b9-ad08-3fd68cbaf349.jpg)
![picon_iptv_fav](https://user-images.githubusercontent.com/7511379/195996485-d91454ab-7367-4186-acca-d39339e07d96.jpg)

Please, show how looks the reference of one of the channels and name of picon file also.

**Comment by luxorko** [comment]
in windows 10 - reference on iptv channel not match (not showing) same as on picon , but when you send bouquet to STB all showing correct! please see screen shot haw reference looks 

![reference](https://user-images.githubusercontent.com/65136999/196005940-13f2ebd7-3864-4502-8c9c-b6daf1bc994b.JPG)

**Comment by luxorko** [comment]
forget mentioned references are copy from epg configuration 
also showing just part of reference see picture

![epg](https://user-images.githubusercontent.com/65136999/196006159-727bebd5-054f-42ed-8344-a60a1b1fcde2.jpg)

**Comment by luxorko** [comment]
can not change reference manually, in iptv or channel bouquet....did you blocked this options

**Comment by luxorko** [comment]
did change reference in bouquet , still cannot see picon
only first number in ref. are diferent 4097 vs 1 should not cause problem ?

![ref1](https://user-images.githubusercontent.com/65136999/196007253-5a69a04d-96b1-4cb7-b504-1ff6d347f412.JPG)

**Comment by DYefremov** [comment]
> only first number in ref. are diferent 4097 vs 1 should not cause problem ?

Yes, that's the cause. Just drag and drop the desired picon from the picons  list (Picons->Explorer tab) to the selected services in the bouquet list, or vice versa the selected services to the desired picon. Your case revealed an important flaw in work with picons. This can be fixed, but... I think it should be combined with [this](https://github.com/DYefremov/DemonEditor/issues/128).

**Comment by luxorko** [comment]
`This can be fixed, but...`
waiting form new version for w10

**Comment by luxorko** [comment]
` Just drag and drop the desired picon from the picons list (Picons->Explorer tab) to the selected services in the bouquet lis`
if you drag picon to iptv channel will be created other picon with reference of iptv 4097_1_....  Dont think is right way 
![image](https://user-images.githubusercontent.com/65136999/196028297-c649a497-a7d3-48a7-991d-dca9d6b03a1e.png)

**Comment by DYefremov** [comment]
>  if you drag picon to iptv channel will be created other picon with reference of iptv 4097_1_.... Dont think is right way

It's all right here. The question is only to the first digit, but it is also acceptable.

**Comment by luxorko** [comment]
test version 3.1.0

picons showing for IPTV channels list - Thank you 

![Capture4](https://user-images.githubusercontent.com/65136999/201497989-0a69b578-7ae2-48c4-b200-50f50dc460d2.JPG)
