### ISSUE TITLE
Extract picon

### ISSUE THREAD

**Issue by mapi68** [DYefremov/DemonEditor#133]
Latest DE for Windows when download picon:

18-10-22 02:42:15 Downloading: https://picon.cz/download/1105
18-10-22 02:42:16 Extracting: 1105
18-10-22 02:42:16 PiconsCzDownloader [extract] error: b'\r\nERROR: C:\\Users\\max\\DemonEditor\\picons\\DM7020HD\\1105.7z : Cannot open the file as archive\r\n\r\n\r\n'
18-10-22 02:42:16 Error: b'\r\nERROR: C:\\Users\\max\\DemonEditor\\picons\\DM7020HD\\1105.7z : Cannot open the file as archive\r\n\r\n\r\n'

In Debian it's ok,

**Comment by DYefremov** [comment]
Win 10:

![picons_download_win10](https://user-images.githubusercontent.com/7511379/196352439-6a3d74a8-765a-4bc8-a6a0-e5552275ce76.png)

I'll test later on Windows 11 also.

**Comment by mapi68** [comment]
It's strange because before today it worked very good (tested in Win10).

**Comment by DYefremov** [comment]
There may be problems with the archive itself. It cannot be ruled out that the  picons author and his service may also have problems. 
Tested on Windows 11:
![picons_download_win11](https://user-images.githubusercontent.com/7511379/196513763-913fb40a-dcb7-44f0-8486-02b941718814.png)

**Comment by DYefremov** [comment]
Do a little experiment. Just install the [latest 7zip](https://www.7-zip.org/a/7z2201-x64.exe) on your system. Without making changes (replacing) in the program files!

**Comment by DYefremov** [comment]
> It's strange because before today it worked very good (tested in Win10).

> Same error....

After some experimentation, I was able to reproduce your case on Windows 10 with **en-us language and locale**!
After installing 7 zip on the system, the error disappeared. But before that, I was playing with regional settings.
![locale](https://user-images.githubusercontent.com/7511379/196734701-5891aea5-3a53-4355-b667-822cae543987.png)

Perhaps it will help.

**Comment by mapi68** [comment]
> After installing 7 zip on the system, the error disappeared.

Yes, after installing it works.

![screenshot_2022_10_19_at_18_38_26](https://user-images.githubusercontent.com/41143572/196752561-98f67528-9ff4-454b-90de-38646055c2c8.png)





Maybe this is a problem after update to Windows 10 2022H2?

**Comment by DYefremov** [comment]
I think you have already answered here: )

> before today it worked very good

**Comment by mapi68** [comment]
With Windows 3.1.0 Alpha the same problem of 7zip picons extractor. 
But if I have 7zip installed in WIndows ([full software](https://www.7-zip.org/a/7z2201-x64.exe)) it extract picons. If I uninstall 7zip stop works!

**Comment by DYefremov** [comment]
No changes have been made in this version. I think it's just missing a certain library.  It needs to experiment. That is why I didn’t really want to include 7zip in to the Windows build, but always used the external option. :)

**Comment by DYefremov** [comment]
Thanks. Updated!
