### ISSUE TITLE
not sure how to call this

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#134]
if you change bouquet name == are not kept same bouquet name in enigma2 setting...meaning if you change name "my stuff" in dameon , but will be save in "enignma 2" like "bouquet.dbe.129"  why cannot have same name like bouquet name you are created?

**Comment by DYefremov** [comment]
![bouquets](https://user-images.githubusercontent.com/7511379/197386926-2cbc673a-89cc-4658-9334-b75b4c57b909.png)

Works for newly created bouquets only!

**Comment by luxorko** [comment]
working like you said, i just changed bouquet name and this way not workin, could be in future?

**Comment by DYefremov** [comment]
> could be in future?

**No.** This is done specifically to prevent problems with the use of some Enigma2 features.
