### ISSUE TITLE
channels mark as "new"

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#136]
some channels are mark as "NEW" and they are colored. - but its very hard to go throught list and "unmark" them.
 Any option to unmark ALL "new" channels in one click, please

![Capture1](https://user-images.githubusercontent.com/65136999/201996610-662b31c0-a01e-444b-bf4e-c5b37b45a686.JPG)

![Capture2](https://user-images.githubusercontent.com/65136999/201996631-fbf666c2-746e-461c-bb80-36d6a16583a0.JPG)

**Comment by DYefremov** [comment]
Yes, I think we can add a separate item to the context menu.

**Comment by DYefremov** [comment]
In addition, if it interferes a lot, you can turn off this option or change the color for these channels.

**Comment by DYefremov** [comment]
Done! Works for selected services only.

![clear_new](https://user-images.githubusercontent.com/7511379/202300647-6eb3c181-5b49-4c11-a056-18d5429e3391.png)

 **Not fully tested!**

**Comment by luxorko** [comment]
yes, working like you said  just " selected services only"
do save channel and open again without "NEW" flag
thank you

**Comment by DYefremov** [comment]
Fine. We can close.
