### ISSUE TITLE
error at start

### ISSUE THREAD

**Issue by dacorsa** [DYefremov/DemonEditor#143]
when i start demoneditor i see this error:

18:51:28 dacorsa@NanoKDE /home/dacorsa $ /app/DemonEditor/start.py 
Gtk-Message: 18:51:31.707: Failed to load module "xapp-gtk3-module"
Traceback (most recent call last):
  File "/app/DemonEditor/start.py", line 28, in <module>
    update_icon()
  File "/app/DemonEditor/start.py", line 9, in update_icon
    with open(icon_name, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] File o directory non esistente: 'demon-editor.desktop'
18:51:31 dacorsa@NanoKDE /home/dacorsa $ 

how solveit?
best regards

**Comment by DYefremov** [comment]
Hi,
**What distro** (version) are you using? How do you run the program?

**Comment by dacorsa** [comment]
hi,
i use ubuntu 22.04 or 22.10, python10 and start with:
 /app/DemonEditor/start.py
or
python3  /app/DemonEditor/start.py

**Comment by DYefremov** [comment]
First of all, you need to read carefully the "Installation and Launch" section of the [README](https://github.com/DYefremov/DemonEditor/blob/master/README.md) .

![Ubuntu_22 10](https://user-images.githubusercontent.com/7511379/209579367-8f7aa8b9-d639-4e82-a38d-ba7dfd4c3314.png)

For Ubuntu, you may need to install the "_python3-requests_" package.
From terminal:
`sudo apt install python3-requests`

For LTS versions, I recommend using the [PPA](https://launchpad.net/~dmitriy-yefremov/+archive/ubuntu/demon-editor) repository.

Best

**Comment by dacorsa** [comment]
Thanks, 
I already installed that package 📦, but I think is a python 10 problem, or of my Python installation

**Comment by DYefremov** [comment]
This app uses the default packages (especially on Ubuntu and derivatives). Usually you don't need to install anything. I recommend you read [this](https://github.com/DYefremov/DemonEditor/issues/4#issuecomment-573313785) also.

**Comment by dacorsa** [comment]
ok thanks after reinstall : 
pip3 install --upgrade requests
now works
