### ISSUE TITLE
description with ":"

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#144]
In the IPTV list - when you change channel name or url (edit)
![Capture](https://user-images.githubusercontent.com/65136999/209580204-31740cd5-4d6b-4d91-a3b0-7cd16e7dc49d.JPG)

after save, bouquet changing -
from 
#DESCRIPTION horror ch+1  
#SERVICE 4097:0:1:....
to
#DESCRIPTION: horror ch+1  
#SERVICE 4097:0:1:....

with colon ":" after DESCRIPTION

**Comment by DYefremov** [comment]
Excluding markers, I always have ':'
Something is not working when loading into the receiver or just worries you?

**Comment by luxorko** [comment]
other plugin in enigma 2 will showing channels name like - 
DESCRIPTION horror ch+1
removing ":" will showing correct channel name horror ch+1

**Comment by DYefremov** [comment]
> other plugin in enigma 2

Are you sure the plugin does this correctly? I have seen both options. Can you tell which one is correct?  No problem to fix it.

**Comment by luxorko** [comment]
jedi-epg-extreme

[https://github.com/kiddac/Jedi-EPG-XStream](url)

during browsing iptv list will showing channel name begining "description"

**Comment by DYefremov** [comment]
OK. Since this is not principal, I changed it to the desired format (without ':').

**Comment by luxorko** [comment]
thank you
could be possible add option "creating add new iptv channel" in the iptv channels list?

**Comment by DYefremov** [comment]
So:
![add_iptv](https://user-images.githubusercontent.com/7511379/209629549-72d55b04-6cd9-47af-bf5a-646d2fb681db.png)
Or like this:
![add_iptv2](https://user-images.githubusercontent.com/7511379/209629594-171e0512-53c7-49bc-b268-b615c045e329.png)

**Comment by luxorko** [comment]
all good, working
