### ISSUE TITLE
copy / paste reference

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#146]
epg copy reference - do copy reference
![image](https://user-images.githubusercontent.com/65136999/210557479-0d159f15-5927-4093-bf23-37dd66e32acb.png)

but when you do paste reference for (IPTV bouquet list) not working 
![image](https://user-images.githubusercontent.com/65136999/210558076-134382ed-fa24-427b-8a24-1563867b18b0.png)

**Comment by DYefremov** [comment]
This does not work?
![assign_ref](https://user-images.githubusercontent.com/7511379/210565118-fd5f8631-1eff-4081-bf73-10108e706669.png)

**Comment by luxorko** [comment]
unfortunately "assign reference" do nothing

**Comment by luxorko** [comment]
only working with channel that have in the front symbol "lock"
![image](https://user-images.githubusercontent.com/65136999/210628040-85ca1b8d-6a7e-4e4f-ae57-7205e6d20da6.png)

**Comment by DYefremov** [comment]
Interesting. Briefly tested on Linux, macOS and Windows 7. Works. I'll try to test later on Windows 10/11. Please specify your OS. Language and Version (Build).

**Comment by luxorko** [comment]
win 10, eng

**Comment by luxorko** [comment]
correction:find it!!

 you cannot assign reference only from "satellite" what been add to current setting, 
channels reference from adding satellite dont assign reference to iptv channel
ps  - they do copy reference correctlly

**Comment by DYefremov** [comment]
Ok. I'll check this.

**Comment by DYefremov** [comment]
I have checked with fresh installed (on VM) Windows 10. Everything works as it should. Maybe I'm doing something wrong or I don't understand you correctly. If possible, please describe step by step what and how you do.

**Comment by DYefremov** [comment]
After several tests, the only thing I found was the lack of assignment of a service type for an IPTV channel when assigning a reference through the context menu. Corrected. I hope this is what you meant.

**Comment by luxorko** [comment]
unfortunatelly not working from all satellite possitions.
- open full setting "vhanibal"  
[-]https://www.linuxsat-support.com/thread/151841-vhannibal-enigma2-setting/?postID=705631#post705631(url)
- add some iptv channel bouquet
- coptv any reference from channel from Astra 28.2 or Astra 19.2
- paste to iptv channel
- nothing imported
if you do same but from Hotbird 13.0 - its working ; ref imported

Any idea?

**Comment by DYefremov** [comment]
Yes. I can confirm. This is bug. And very interesting one. Already fixed. I hope.:)

**Comment by luxorko** [comment]
perfect, now working
