### ISSUE TITLE
epg configuration - more filter

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#148]
could be possible to add more filter for epg configuration - like satellite possition?
![ccc](https://user-images.githubusercontent.com/65136999/213686176-7b42d660-2ba9-4643-a6b1-b532ddad87c5.JPG)
filter by sat. possition you have for bouquets
![1000](https://user-images.githubusercontent.com/65136999/213686814-254e442d-d59f-4f0a-9c0f-8f6e8a5eadd1.JPG)

please make same for epg configuration card
![bbb](https://user-images.githubusercontent.com/65136999/213686470-40c9e17c-21a6-4c9b-8bcf-d0fe88d5b3df.JPG)
Thank you

**Comment by DYefremov** [comment]
Ок. I'll think about it. Possible as an multiple filter option (as for the picons tab).
![filter](https://user-images.githubusercontent.com/7511379/213694756-87470de1-4b06-4b9a-9290-d23b986fa298.png)

**Comment by luxorko** [comment]
i would say better have filter by satellite possitions, it faster to to find actuall channel for user
etc;
sky are on 28.2uk; 19.2de and 13.0it
if you have iptv list sky it. then choose filter possition 13  
then just auto parse or drag&drop

for - multiple filter option:
if you just wrote sky then will show all sky and need to be very carefull with one is right for user
if you do auto parse then demon will parse first match channel nane.

please make filter by satellite

**Comment by DYefremov** [comment]
Ок. For now just a prototype. :)

![filter](https://user-images.githubusercontent.com/7511379/213866220-cd6c7c7e-2ea8-4f64-92a5-88b28fe428a3.png)

**Comment by luxorko** [comment]
excellent job, thank you

**Comment by luxorko** [comment]
hurried, selection by sattelite showing but acctually deamon still make "search and parse" from whole (ALL) channels , instead from selected .
could you look at this please
