### ISSUE TITLE
iptv stream not working

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#149]
v3.2.4 stream not working; last v3.2.3 stream OK.

could you check please. 
thank you

![image](https://user-images.githubusercontent.com/65136999/213887018-882e9625-b9c7-4215-a59e-5b9e3fc241b3.png)

**Comment by DYefremov** [comment]
It's strange. It doesn't work for me with version 3.2.3 either. Apparently the problem with the latest update of the libraries. Looks like some libraries are missing. I repackaged the build with a set of libraries from version 3.2.2. Please test!

**Comment by DYefremov** [comment]
Checked. Should work.
