### ISSUE TITLE
Time split in EPG

### ISSUE THREAD

**Issue by mapi68** [DYefremov/DemonEditor#150]
It will be useful if time in EPG may be split in 2 columns
![screenshot_2023_01_23_at_20_23_12](https://user-images.githubusercontent.com/41143572/214135545-f46fb8c1-1fd8-402e-bc42-10964b640d9b.png)

**Comment by DYefremov** [comment]
If we are talking about the EPG tab, then personally I do not see any practical sense in this. At least for now. What is actually the benefit of this? In addition, this display option apparently makes sense to put it on the tab itself. Or in the "View" menu.

![EPG_time_split](https://user-images.githubusercontent.com/7511379/214140850-50fc777d-9da0-4e64-8cb2-016c4bf192e8.png)

But I'm willing to discuss. Perhaps there will be more suggestions or someone else will express their opinion.

**Comment by mapi68** [comment]
For example with multiple EPG you can put "End time" in Time order and see whar program is ending now (useful to watch after something from the begin)

**Comment by DYefremov** [comment]
Ок. I don't see any big problems in implementing this feature. Perhaps there is a sense to make such view as permanent.

> Perhaps there will be more suggestions or someone else will express their opinion.

**Comment by DYefremov** [comment]
Did a few tests. Yes, it will take some work, but... The main question, oddly enough, is how to display time values (in what format).
![EPG time](https://user-images.githubusercontent.com/7511379/214247039-44f64563-3681-4f0e-bcb1-5360dd703cb8.png)

With date,  day of the week, etc.

**Comment by mapi68** [comment]
![screenshot_2023_01_24_at_11_14_07](https://user-images.githubusercontent.com/41143572/214268457-373705f3-92fa-4de6-8459-592212689986.png)

**Comment by DYefremov** [comment]
Hmm. Yes, looks ok.

**Comment by mapi68** [comment]
Maybe another column with "Length"(in my screenshot: 02h 20m)?

**Comment by DYefremov** [comment]
Yes, it's possible. We need to test how will it look.

**Comment by DYefremov** [comment]
Probably so:
![epg](https://user-images.githubusercontent.com/7511379/214298038-a2b8d054-068e-4afb-a75b-1cfa947ecfe8.png)

**Comment by DYefremov** [comment]
Almost done. :) 
It remains to decide on the time format for the duration column. I think it is desirable to use localized names.
Here already existing ones in *.po files. 
![duration](https://user-images.githubusercontent.com/7511379/214557585-0ac242a2-5f32-4596-988d-2120c24bf535.png)

Perhaps it is worth converting to lower case and remove the spaces between the values.

**Comment by mapi68** [comment]
But for example in Italian must be:
0 ore
1 ora
2 ore
3 ore
......
It's more simple 00h 50m

**Comment by DYefremov** [comment]
> 0 ore
> 1 ora

Yes, for other languages also. As an option, use the first letter in lower case without spaces. For Russian and Belarusian translations  languages this approach is used initially. For me personally, this is not very important, but for other users questions may arise. The day of the week is translated and the hours and minutes are in English.

**Comment by mapi68** [comment]
Could you enlarge the "Title" item by a few characters and "Start" and "End" by one character, because the last number remains hidden?
![Screenshot_20230125_175616](https://user-images.githubusercontent.com/41143572/214631846-f0041f6f-3a9b-445b-8569-82857c86191c.png)ì

**Comment by DYefremov** [comment]
Made. Test again.

**Comment by mapi68** [comment]
It's the same, it doesn't change

**Comment by DYefremov** [comment]
Strange. It worked for me. Changed through another option.

**Comment by DYefremov** [comment]
There is no need for that pull request. My first option **should** have worked! Still, Gtk+ sometimes infuriates me. Looks like I'll have to devote more time [to this](https://github.com/DYefremov/E2Toolkit) project. :)
What distro and version are you using?

**Comment by mapi68** [comment]
Debian 11

**Comment by DYefremov** [comment]
What desktop?

**Comment by DYefremov** [comment]
With this variant the size should adjust automatically.

**Comment by mapi68** [comment]
OK, perfect!!!! Yes it's KDE.

**Comment by DYefremov** [comment]
Also tested in Debian 11 KDE and Kubuntu.Yes. Looks as working. :) I think we can close.
