### ISSUE TITLE
picon location

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#157]
cannot manually change location for transfer picons
writing manually - and demon will adding endline these `"\" `see picture

so cannot trasfering new picons 

could you add to locatian for picon please
/usr/share/enigma2/picon 
/hdd/picon
/usb/picon

![image](https://user-images.githubusercontent.com/65136999/219417611-29ae5c27-2aab-46f9-8bf6-67e2351c6896.png)

**Comment by DYefremov** [comment]
Hi,

> /usr/share/enigma2/picon

This path is present by default. 
![picons_path](https://user-images.githubusercontent.com/7511379/219431429-96147d85-17c7-461b-8de9-e43f0ffc6fe3.png)
Perhaps you removed it. After resetting the settings should appear again.

> /hdd/picon
> /usb/picon

Added to defaults. It should also appear after settings reset.

> demon will adding endline these `"\"`

I think it's related to Windows build only. Corrected.

**Comment by luxorko** [comment]
ok 
maybe have option "blank" do not import picon at all?
yes /no ?

**Comment by DYefremov** [comment]
> option "blank" do not import picon at all?

Hmm, I don't quite understand what you mean.

**Comment by luxorko** [comment]
you can choose where should be transfer picon to receiver
but of user dont wanna have picons becouse old receiver are slow?

he can see picons in demon but make "block-do not transfering" any to reciver/hdd/usb ...

**Comment by DYefremov** [comment]
> he can see picons in demon but make "block-do not transfering" any to reciver/hdd/usb ...

And what forces you to load picons into the receiver now?  Just don't download.  To display in the program, you do not need to have piсons in the receiver at all. I have several thousand picons on my computer (to display im DemonEditor), and in the receiver only those that are in my favorite lists (about 70). You can download the desired picons from the Web or add from a local folder:
![picons](https://user-images.githubusercontent.com/7511379/219469829-561700b9-8f96-4355-9257-63e3ac62dfc8.png)
You can download only the necessary piсons by simply selecting the ones you need from the list and clicking the "Download" button.
