### ISSUE TITLE
channel list

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#159]
hi just note possibility to adding 2x same channel (with same name; frequency and ref. number) to one bouquet and he showing in TV. 
testing to adding 10x same channels and Demon did and transfer to STB.  its non-sense to have this.

could you make block to adding 2x or more same channels in one bouquet?

**Comment by luxorko** [comment]
same think happens with IPTV - you can add same channel (name, url and ref.number ) to one bouquet,as many times as you can.

**Comment by DYefremov** [comment]
Hi,
> could you make block to adding 2x or more same channels in one bouquet?

I know and it's ok! But I probably won't do it.
1. Enigma allows it.
2. When adding several channels at once to large lists, this may lead to performance degradation. Yes, this can be somewhat optimized, but .. Perhaps it is better to use the context menu:

![mark_duplicates](https://user-images.githubusercontent.com/7511379/220434113-890ce04a-b062-40cb-bbde-6d99edadd35d.png)

**Comment by luxorko** [comment]
OK
just test you must click on that channel what has more copies 

better will be - remove ALL duplicate in bouquet

what do you think

**Comment by luxorko** [comment]
and for IPTV channel will be working as well?
same url means same stream = there should not be multiple channels with the same url in the favorites list.

**Comment by DYefremov** [comment]
Reference and URL together.

**Comment by luxorko** [comment]
Regarding satellite channels bouquet - working correct 

Regarding IPTV bouquet:
`Reference and URL together.`
very hight possibility same stream IPTV are have simular name (Cinema Uk; Cinema HD, CinemaFHD ... provider/person who creating m3u list can give them any references), but are URL stay same! Same URL means meanig same stream = and should be classified like duplicated channel
i would change code for deleting duplicate just for same url steam address.

And you?

**Comment by DYefremov** [comment]
> And you?

Disagree.
 The user himself must decide what and how he should have in the list! Only reference + URL in the case of IPTV gives confidence that these channels are identical (This combination is also an ID for the IPTV channel). In addition, the logic of working with IPTV should not differ much from other types of channels (where the channel ID is its reference). If you need special handling of the list (e.g, remove all channels starting with the letter "A"), now we have [extensions](https://github.com/DYefremov/demoneditor-extensions).  E.g. You can implement a function that removes channels with the same references or URLs from all lists (bouquets). Etc. And the user will know exactly what the function does.

**Comment by luxorko** [comment]
`now we have [extensions](https://github.com/DYefremov/demoneditor-extensions).`
have both extension
![image](https://user-images.githubusercontent.com/65136999/221413431-e53f12e3-56c5-4810-a12a-483c29823ae6.png)

opening bouquet.tv - nothing showing 
please give hint how to using this extension for removing from IPTV_bouquet.tv same URL  channels

![image](https://user-images.githubusercontent.com/65136999/221413620-afba7da8-450d-430b-8820-bca7b6abc6ed.png)

**Comment by DYefremov** [comment]
This is an extension for advanced playlist import (\***m3u**). Both from files and text representation (from the clipboard).
Please, create a separate request for you case[ here](https://github.com/DYefremov/demoneditor-extensions/issues).
