### ISSUE TITLE
import sat&channels from websites

### ISSUE THREAD

**Issue by data84** [DYefremov/DemonEditor#16]
hi
This is a great app for linux :)

can you, in the future, add the option to import satellites and channels from lyngsat.com, kingofsat.net or others websites?

It would be a useful option for creating new lists, but it is not available in many applications of this type.
 Probably only the paid version of "echannelizer" has this option working now.

/sorry for my English :) 
 Regards data84

**Comment by DYefremov** [comment]
Hi.
Look carefully in the satellites edit tool. This feature already exists!
Best regards

![satellites](https://user-images.githubusercontent.com/7511379/77222481-90e43d00-6b64-11ea-9810-2b071af93a9e.png)

**Comment by DYefremov** [comment]
Hi.
Look carefully in the satellites edit tool. This feature already exists!

![satellites](https://user-images.githubusercontent.com/7511379/77222481-90e43d00-6b64-11ea-9810-2b071af93a9e.png)

I’ve already thought about importing channels, but I have postponed it for now. Perhaps in future versions I’ll add it.
My English is also far from perfect! :)
Best regards

**Comment by data84** [comment]
Yes yes , 
I see the sat updates from lyngsat or flysat. 
I tested it. It works very good , but it can be useful to download channels as well from web: 
1. to one or several transponders
2. to one several satellites 



.....:)
And very very very later;) version,  maybe you add the function conversion to other channel list formats

**Comment by DYefremov** [comment]
>maybe you add the function conversion to other channel list formats

Hi
If you mean the conversion from ver .4 to lamedb5, then this functionality is already there.
Just load the list of channels in the old format, and then turn on ver. 5 support in the settings and save! Later I will add the menu item "Save as ...".  Usually, users rarely use this feature (just uses one default format), including me. :)

Best regards

**Comment by data84** [comment]
I mean conversion to a different format than e2, but it is not important now :)

**Comment by DYefremov** [comment]
Ok. Then have a good tests! :+1:

**Comment by DYefremov** [comment]
>it can be useful to download channels as well from web:
>     1. to one or several transponders
>     2. to one several satellites

Added **experimental** implementation for this  feature. So far, only basic functionality. Will be gradually improved.
![web_import](https://user-images.githubusercontent.com/7511379/97909451-4c0ac080-1d59-11eb-9626-85bed91f7ccc.png)
