### ISSUE TITLE
Merge multiple transponder lists in a single orbital position ?

### ISSUE THREAD

**Issue by lgrawet** [DYefremov/DemonEditor#165]
Hi,

When updating transponder lists from Kingofsat (or LyngSat...), is it possible to merge transponder lists on the same orbital position ?
For example, Hot Bird will be splitted in three transponder lists and the preexisting 13E of the file will be left untouched. (open)enigma will then complain about invalid satellites.xml file

13.0°E 	Hot Bird 13B
13.0°E 	Hot Bird 13E
13.0°E 	Hot Bird 13C

Thank you,

Laurent

**Comment by DYefremov** [comment]
Hi,
I think it's possible. E.g as an additional option:
![merge](https://user-images.githubusercontent.com/7511379/224466967-359b25b7-f63e-4aec-9f4b-a0464b20dc69.png)

**Comment by DYefremov** [comment]
Added base implementation. Not fully tested!
