### ISSUE TITLE
DemonEditor-3.5.0-Beta.deb gives "550 failed to change directory"

### ISSUE THREAD

**Issue by hugocoolens** [DYefremov/DemonEditor#168]
I installed DemonEditor-3.5.0-Beta.deb on Linux Mint 21. I entered the ip adres, port, password... of my receiver and did a connection test which was successful. Unfortunately when trying to fetch the data from my receiver to the computer I always get the
error "550 failed to change directory". Is this a bug or am I doing something wrong?

**Comment by DYefremov** [comment]
Problem with FTP access to files on your Box. 
1. Check that the Enigma2 paths are correct:
![settings](https://user-images.githubusercontent.com/7511379/224768590-37a9a04b-f69e-4eef-8209-b3536665231e.png)
2. For all recent Enigma2 images, it is mandatory to **set a password** for "root" user. Without this, there will be no access also.
On your Box : System->Network->Password Setup

For more information, look on the support forums for your image.

**Comment by hugocoolens** [comment]
> 

Thanks this solved the issue

**Comment by hugocoolens** [comment]
thanks, problem solved

kind regards,
Hugo
p.s. is it possible to send a reload command to the receiver?

**Comment by DYefremov** [comment]
If the HTTP API is enabled, then this request is called automatically.
![reload](https://user-images.githubusercontent.com/7511379/225332388-fb5f8a47-3353-4fe6-9e4d-4975248f7d08.png)

**Comment by hugocoolens** [comment]
OK, thanks!

kind regards,
Hugo
