### ISSUE TITLE
deleting working stream

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#187]
testing demon 3.8.0alph;  Win10

IPTV - remove all unavaiable = lost working streams are deleteng 
could you check please 

`https://cp1.server89.com:19360/dasberni/dasberni.m3u8`

![image](https://github.com/DYefremov/DemonEditor/assets/65136999/e3a1c147-a03d-49ab-92e7-9efbd7b0d1fc)

**Comment by DYefremov** [comment]
I don't see any problems with this stream. Doesn't delete anything for me.

**Comment by luxorko** [comment]
he does

please use same ref. number 

`4097_0_1_3604_3565_650d_1010101_0_0_0`

if you have ref number basic - `4097_0_1_0_0_0_0_0_0_0`

channel are not deleting...

**Comment by DYefremov** [comment]
> he does

At me doesn't.

![ref](https://github.com/DYefremov/DemonEditor/assets/7511379/76dbf4c3-a884-440d-99e8-d7c358e52662)
![test](https://github.com/DYefremov/DemonEditor/assets/7511379/719a8f5e-3d31-4d12-b3ff-3ec20a4fb2f8)

**Comment by luxorko** [comment]
strange, maybe becouse im WIN10?

**Comment by DYefremov** [comment]
On screenshots Windows 10 also.

**Comment by luxorko** [comment]
what could be difference?
any ide?

i see you did some update on demon
my wersion are from 06 sep ..do you have same or new one?

**Comment by DYefremov** [comment]
I tested with [this version](https://github.com/DYefremov/DemonEditor/releases/tag/3.8.0-a1).

**Comment by luxorko** [comment]
im using same...

**Comment by luxorko** [comment]
Could yu check my bouquet, plese 
...all streams will deleting....
"IPTV- Remove all unavaibe"

[
[userbouquet.e2m3u2b_italia-tuvi_new-broadcasts.tv.txt](https://github.com/DYefremov/DemonEditor/files/13257585/userbouquet.e2m3u2b_italia-tuvi_new-broadcasts.tv.txt)
](url)

**Comment by DYefremov** [comment]
> im using same...

Depending your screenshot this is an older version. Show your About dialog!

**Comment by luxorko** [comment]
![image](https://github.com/DYefremov/DemonEditor/assets/65136999/61e01d0f-ad3d-4625-b2a2-b67db2d0178e)

**Comment by luxorko** [comment]
> Could yu check my bouquet, plese ...all streams will deleting.... "IPTV- Remove all unavaibe"
> 
> [ [userbouquet.e2m3u2b_italia-tuvi_new-broadcasts.tv.txt](https://github.com/DYefremov/DemonEditor/files/13257585/userbouquet.e2m3u2b_italia-tuvi_new-broadcasts.tv.txt) ](url)

just remove ".txt "

**Comment by DYefremov** [comment]
Download again and run from the unpacked folder. Perhaps you unpacked over an old version or something similar.

**Comment by luxorko** [comment]
done. but same story.... streams deleted

![image](https://github.com/DYefremov/DemonEditor/assets/65136999/4e4b3cde-112e-4806-a930-e78777c0b048)

**Comment by luxorko** [comment]
fill list/bouquets
![image](https://github.com/DYefremov/DemonEditor/assets/65136999/531ed67c-03ab-40f7-973b-42cde532e497)

after "remove all unavaiable" stsays just marker
![image](https://github.com/DYefremov/DemonEditor/assets/65136999/b2ae76c3-f284-426c-8303-2968681071d1)

**Comment by luxorko** [comment]
did you test sending bouquet?

**Comment by DYefremov** [comment]
Yes. I’m not completely sure of the correctness of this file, but I see one potential problem. Perhaps this is really a bug. I'll take a closer look later.

**Comment by luxorko** [comment]
> I'll take a closer look later.

hope you will find and fix bug and new version will be relesed
thank you for hard work

**Comment by luxorko** [comment]
thank you, believe is working
could you relesed new version for Win10 please

**Comment by DYefremov** [comment]
[Test builds.](https://github.com/DYefremov/DemonEditor/releases/tag/3.8.0-test)
