### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#188]
Win10 report virus, when opening "DemonEditor.exe"

![image](https://github.com/DYefremov/DemonEditor/assets/65136999/ca7e6b44-48ce-429c-95bf-349778da2c16)

**Comment by DYefremov** [comment]
Sometimes Microsoft Defender and some other antiviruses may perceive executable files created by PyInstaller as potentially dangerous.Of course there are no viruses there. If you have doubts, you can check this file using third party services or utilities, or not use the file or build.

**Comment by luxorko** [comment]
"DemonEditor.exe" - was deleting (any trick to prevent file deletion?)
"DemonEditor-dbg" - working fine

**Comment by DYefremov** [comment]
[Perhaps so](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26).

**Comment by luxorko** [comment]
fantastic  
actual version 3.8.0 - working with Win11 
no more "virus" report from Windows

thank you

**Comment by luxorko** [comment]
hi im sorry but windows again reporting virus v3.9.1beta 
anyway previous v3.9.0beta - no issue and working 
could you be able to check please

![image](https://github.com/DYefremov/DemonEditor/assets/65136999/08beca77-6f84-47d1-89ec-f560ad34b1b4)

**Comment by DYefremov** [comment]
Hi
Unfortunately, I cannot add anything new to what has been [written already](https://github.com/DYefremov/DemonEditor/issues/188#issuecomment-1802374483).
In addition, if you wish, you can also [submit the file to Microsoft for malware analysis](https://www.microsoft.com/en-us/wdsi/filesubmission).
