### ISSUE TITLE
Picons import IPTV

### ISSUE THREAD

**Issue by marcus83ita** [DYefremov/DemonEditor#190]
hi!

can you add picon import to IPTV?
![ScreenShot-OSX 2023-12-14 alle 05 49 57](https://github.com/DYefremov/DemonEditor/assets/123148362/50206a2e-1776-40b2-a3a1-e2aa51343806)

**Comment by DYefremov** [comment]
This feature will be only active if the playlist contains links to logos!

![import picons](https://github.com/DYefremov/DemonEditor/assets/7511379/dc686f02-4d6b-4757-aa45-dfee75449ee5)
