### ISSUE TITLE
Bug in "mark not present in bouquets"

### ISSUE THREAD

**Issue by risky777** [DYefremov/DemonEditor#197]
There seems to be a bug in "app/ui/main.py" in function "mark_not_in_bouquets". Critical code looks like:

if fav_id not in ids:
	row[Column.SRV_BACKGROUND] = self._EXTRA_COLOR
	
and it should look like:

if fav_id not in ids:
        row[Column.SRV_BACKGROUND] = self._EXTRA_COLOR
    else:
        row[Column.SRV_BACKGROUND] = self.get_new_background(row[Column.SRV_CAS_FLAGS])

(I've copied "else" from function "clear_marked")

At present, on table services context-menu "Mark not present in Bouquets" behaves like this:
- run "Mark not present in Bouquets" and it works correctly
- copy one service not present in bouquets from services-list to favorites-list
- run "Mark not present in Bouquets" and it doesn't change anything because background of added service is not changed.

**Comment by DYefremov** [comment]
Yes, this is a bug. Corrected.
