### ISSUE TITLE
Ubuntu 14.04.5 LTS x64 syntax error

### ISSUE THREAD

**Issue by pczolee** [DYefremov/DemonEditor#2]
Hello.

I have Ubuntu 14.04.5 LTS x64 installed. I tried to run your program, but is have syntax error:

start.py
Traceback (most recent call last):
  File "./start.py", line 2, in <module>
    from app.ui.main_app_window import start_app
  File "/home/user/DemonEditor-master/app/ui/main_app_window.py", line 785
    srv = Service(*agr[0:2], icon, srv.name, *agr[0:3], s_type.name, self._picons.get(picon_id, None),
                                             ^
SyntaxError: invalid syntax

Because this is LTS, i don't want to update, but, can you help me how to run it?

Thanks

**Comment by pczolee** [comment]
Hello.

Thanks for your answer. I understand you, but some people don't want to use the latest ubuntu, because the old LTS is still supported and working fine. Anyway, thank you very much for your help. Now it is running. Only one problem what I found is, that the menu title font/language is Cyrillic.
Thank you for your time to help me and other who want to run it in old version.

I wish you all the best an Merry Christmas!

**Comment by DYefremov** [comment]
Hello. 

Happy to help.
I checked the problems with fonts and languages on the live system and I do not observe it.
Until I will not close this issue. Maybe I will sometimes add changes to [this](https://github.com/DYefremov/DemonEditor/tree/win_test) brunch.

Merry Christmas!

**Comment by DYefremov** [comment]
I have updated the functionality to version **3.2** and added a part from later versions!

Best regards

**Comment by DYefremov** [comment]
I have updated the functionality to version 3.2 and added a part from later versions!

Best regards

**Comment by pczolee** [comment]
Hello.

First of all, thanks for your fast reply! Unfortunately the new version is not running :(

$ ./start.py
Traceback (most recent call last):
  File "./start.py", line 2, in <module>
    from app.ui.main_app_window import start_app
  File "/home/user/DreamEditor/DemonEditor-win_test/app/ui/main_app_window.py", line 24, in <module>
    from .satellites_dialog import show_satellites_dialog
  File "/home/user/DreamEditor/DemonEditor-win_test/app/ui/satellites_dialog.py", line 8, in <module>
    from app.tools.satellites import SatellitesParser, SatelliteSource
  File "/home/user/DreamEditor/DemonEditor-win_test/app/tools/satellites.py", line 5, in <module>
    import requests
ImportError: No module named 'requests'

**Comment by pczolee** [comment]
Solved by install python3-requests.

Unfortunately the menu title language is still Cyrillic (in the menu everything is in my locale).

$ ./start.py

(start.py:28900): Gtk-WARNING **: Unknown property: GtkPaned.wide-handle

(start.py:28900): Gtk-WARNING **: Unknown property: GtkPaned.wide-handle

(start.py:28900): Gtk-WARNING **: Unknown property: GtkPaned.wide-handle

(start.py:28900): Gtk-CRITICAL **: gtk_application_get_app_menu: assertion 'GTK_IS_APPLICATION (application)' failed

(start.py:28900): Gtk-CRITICAL **: gtk_application_get_menubar: assertion 'GTK_IS_APPLICATION (application)' failed

(start.py:28900): Gtk-CRITICAL **: gtk_radio_button_set_group: assertion '!g_slist_find (group, radio_button)' failed

**Comment by DYefremov** [comment]
Hello.

At the moment, you can ignore this warnings. More interesting, what is the problem with your locale. Can you send a screenshot for explanation + output of the "locale" command in the terminal? On the live system, I don't see any Cyrillic characters. In my spare time I will try to look this problem.

Best regards

**Comment by pczolee** [comment]
Hello.

Thanks for your time. Here you can find the screenshot: https://ufile.io/ljvd2 

$ locale
LANG=hu_HU.UTF-8
LANGUAGE=hu_HU
LC_CTYPE="hu_HU.UTF-8"
LC_NUMERIC="hu_HU.UTF-8"
LC_TIME="hu_HU.UTF-8"
LC_COLLATE="hu_HU.UTF-8"
LC_MONETARY="hu_HU.UTF-8"
LC_MESSAGES="hu_HU.UTF-8"
LC_PAPER="hu_HU.UTF-8"
LC_NAME="hu_HU.UTF-8"
LC_ADDRESS="hu_HU.UTF-8"
LC_TELEPHONE="hu_HU.UTF-8"
LC_MEASUREMENT="hu_HU.UTF-8"
LC_IDENTIFICATION="hu_HU.UTF-8"
LC_ALL=

**Comment by DYefremov** [comment]
Hello.

Yes, you were right. :) I uploaded a small fix. Now the menu titles must be in English. 

Best regards

**Comment by pczolee** [comment]
Hello.

Yes, now it is english! Fine, thank you!

I wish you a happy new year!

Best Regards
