### ISSUE TITLE
epg configuration - missing url

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#209]
after adding references and click to "apply"
![image](https://github.com/user-attachments/assets/07ab9c93-425c-4eeb-a0e3-f04a59960b36)

 all urls disappear - delete   using 3.11.2beta

**Comment by DYefremov** [comment]
Hi,
Interesting case! Looks like changes in Python itself. :) 
Thx for the report. Should be fixed, but needs more testing.

**Comment by DYefremov** [comment]
Hi, Please test [this](https://github.com/DYefremov/DemonEditor/releases/tag/3.11.3-b1) build!

**Comment by luxorko** [comment]
> Hi, Please test [this](https://github.com/DYefremov/DemonEditor/releases/tag/3.11.3-b1) build!
hi confirm it is working properly now. thank you

I would like to ask if it will be possible to speed up the automatic selection?
now only works if channels name are 100% mach.

just found it on another forum, maybe it could help improve "automatically adding links to IPTV channels"

`https://www.linuxsat-support.com/thread/130052-plugin-e2m3u2bouquet/?postID=832758#post832758`

**Comment by DYefremov** [comment]
> maybe it could help improve "automatically adding links to IPTV channels"

Yeah, I already thought about something like that. I think it would work for certain cases. Maybe it makes sense to make it optional. For example "Deep Search" etc. The only question is performance. Here needs to experiment.

At the moment we close this.
