### ISSUE TITLE
play stream from "services"

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#211]
hello , could be possible to have play iptv from section "services" ?

thank you
![image](https://github.com/user-attachments/assets/b46f4ef4-ddfd-41c0-b600-24b04b97b9a4)

**Comment by DYefremov** [comment]
Hi,
Is this option enabled?
![settings](https://github.com/user-attachments/assets/74dae758-e4de-4287-b9ec-157ceee4ffa0)

**Comment by luxorko** [comment]
sorted. thank you
