### ISSUE TITLE
DemonEditor doesn't start on mac

### ISSUE THREAD

**Issue by hiduser0** [DYefremov/DemonEditor#28]
./start.py 
Traceback (most recent call last):
  File "./start.py", line 26, in <module>
    from app.ui.main_app_window import start_app
  File "/Users/user/Downloads/DemonEditor-master/app/ui/main_app_window.py", line 8, in <module>
    from gi.repository import GLib, Gio
ModuleNotFoundError: No module named 'gi'

**Comment by DYefremov** [comment]
Hello.
To get started, I recommend using a separate [branch](https://github.com/DYefremov/DemonEditor/tree/experimental-mac) for macOS. The [README](https://github.com/DYefremov/DemonEditor/blob/experimental-mac/README.md) describes everything you need to run the program on macOS. If you just want a ready-made macOS package, then among the [releases](https://github.com/DYefremov/DemonEditor/releases/tag/1.0.0-macOS) you can find a ready-made ***.dmg** file. Нere is a direct [link](https://github.com/DYefremov/DemonEditor/releases/download/1.0.0-macOS/DemonEditor.dmg) to the latest build. In the **security settings** it will be necessary to allow the launch of this application!
**Important.** The macOS version is currently in experimental status!
Best

**Comment by hiduser0** [comment]
Thank You
