### ISSUE TITLE
Renaming bouquet bug

### ISSUE THREAD

**Issue by vpont** [DYefremov/DemonEditor#33]
I've found out that renaming a bouquet results in losing all the custom renames of the services in that bouquet.
Way to reproduce:

1. Rename a few services in a bouquet with "Rename for this bouquet"
2. Rename the bouquet (Ctrl-E)
3. Change the active bouquet
4. Go back to the renamed bouquet

Now all renamed services will have the default names.

**Comment by DYefremov** [comment]
Hi. Please [test it](https://github.com/DYefremov/DemonEditor/archive/development.zip).

**Comment by vpont** [comment]
I can confirm it's working as expected now :+1:
