### ISSUE TITLE
Feature: show SID as decimal instead of hex

### ISSUE THREAD

**Issue by vpont** [DYefremov/DemonEditor#34]
In services' list it would really help me when comparing services with KingOfSat if one could choose between showing services' SIDs as decimal or hex numbers.

![image](https://user-images.githubusercontent.com/3983093/92445047-0ea01180-f1b4-11ea-8aeb-12520faf0fbc.png)

**Comment by DYefremov** [comment]
I think it will be useful. As an option, I can offer a context (pop-up) menu for the column header with the choice of the desired display.

**Comment by DYefremov** [comment]
Hi. Hey. I made a test implementation of this function.Perhaps she will suit you.  But...
![sid_as_decimal](https://user-images.githubusercontent.com/7511379/92971525-48f60100-f489-11ea-91a6-1940076a3bfc.png)
[DemonEditor_sid_as_decimal.zip](https://github.com/DYefremov/DemonEditor/files/5211444/DemonEditor_sid_as_decimal.zip)

Unfortunately on big data (> 5000 rows in the main list) it can be slow. I tried several options and came to the conclusion that it would be optimal to do the following:
**Option 1.**
We just add the options to show in tooltips as decimal!
**Option 2.**
We convert the values when loading data and again show them in tooltips. But here it is already desirable to restart the program!
**Option 3.**
Or we leave this test option(with popup menu) that is in the attachment.

Personally, I tend to the **first** option. I will be glad for your thoughts.

**Comment by vpont** [comment]
Hi.
What about keeping it simple and just add the SID in the tooltip in both formats, like this:
![image](https://user-images.githubusercontent.com/3983093/92990078-428f7580-f4d9-11ea-803e-ebb2f1885a5c.png)
No extra config options or reloads.

**Comment by DYefremov** [comment]
Hi. Yes, that's a **good option**! We only need to select a display location in the main list. Alternatively after the service type or on the next line. I think the first option.

**Comment by vpont** [comment]
Maybe after the service type, in order to maintain consistency with the main window list?

**Comment by DYefremov** [comment]
Yes, it look ok too. Please [test it](https://github.com/DYefremov/DemonEditor/archive/development.zip).

**Comment by vpont** [comment]
Looks good to me!
Just that extra space in front of the decimal value:
![image](https://user-images.githubusercontent.com/3983093/92991845-a2d8e400-f4e6-11ea-9ab9-74f71688b78f.png)

**Comment by vpont** [comment]
And the hex value would look cleaner in upercase

**Comment by DYefremov** [comment]
Ok. [Done](https://github.com/DYefremov/DemonEditor/archive/development.zip)!

**Comment by vpont** [comment]
Looks good, thank you!!
