### ISSUE TITLE
'utf-8' codec can't decode byte 0x88 in position 712: invalid start byte

### ISSUE THREAD

**Issue by shmoxy75** [DYefremov/DemonEditor#37]
I got this error when trying to receive from receiver:
'utf-8' codec can't decode byte 0x88 in position 712: invalid start byte

**Comment by DYefremov** [comment]
Hello.
It looks like you have files in the path `/etc/enigma2` with unreadable characters (in a different encoding) in their names.
I made some changes to data loading. Perhaps this will help. If you are using Linux then [test this](https://github.com/DYefremov/DemonEditor/archive/development.zip).

**Comment by DYefremov** [comment]
The Bug can really arise if there are files in the settings dirs with names in an encoding other than UTF-8 and having characters that are absent in ASCII.
