### ISSUE TITLE
control box

### ISSUE THREAD

**Issue by michaeladams123** [DYefremov/DemonEditor#38]
Hi,

Many thanks for your kindly support,

I need to ask you if possible to control the enigma2 box like reboot ? and send full scan command and configure the tuners ?

Best Regards

**Comment by DYefremov** [comment]
Hi,
There is no such possibility at the moment. But it is planned to improve the capabilities of the HTTP-API and add a pop-up panel with a certain set of buttons (similar to the remote control) and more advanced information than in the status bar. I think a prototype of this feature will be already available in the next version.

Best
