### ISSUE TITLE
Update 0.4.8 Pre-alpha (Build: 20200507)

### ISSUE THREAD

**Issue by mischugo** [DYefremov/DemonEditor#39]
Sorry for the question, but I am not a developer... And I have no idea how else to contact you. Is there a way to update an earlier version? If so, how do I do that

Thank you so much for this great piece of software

Best - Maik

**Comment by DYefremov** [comment]
Hello, Mike.

After version 1.0.0 you can download the ready-made packages as a _*.dmg_ file from the [releases](https://github.com/DYefremov/DemonEditor/releases) page.
![Снимок экрана в 2020-11-13 20-32-10](https://user-images.githubusercontent.com/7511379/99104519-2485e480-25f2-11eb-9aeb-768167349a5c.png)

Here's the[ latest version](https://github.com/DYefremov/DemonEditor/releases/download/1.0.1-b1-macOS/DemonEditor.dmg) for macOS. It is advisable to uninstall the previous version before installing!
For more info, you can read [here](https://github.com/DYefremov/DemonEditor/tree/experimental-mac).

Best
Dmitriy

**Comment by mischugo** [comment]
Hello Dimitriy,

thank you so much for teh fast response.
I was on that page, but it looks other then your screenshot

There was no *.dmg file

That’s why i asked in github



Is it like this, that i only delete the older version or is there a must for any uninstaller?


Best

Maik





Am 13. Nov. 2020, 18:54 +0100 schrieb Dmitriy Yefremov <notifications@github.com>:

**Comment by DYefremov** [comment]
> Is it like this, that i only delete the older version or is there a must for any uninstaller?
Just move to trash from the Applications folder.

Best
Dmitriy

**Comment by mischugo** [comment]
Thanks a lot!!!!!
Am 13. Nov. 2020, 19:43 +0100 schrieb Dmitriy Yefremov <notifications@github.com>:
