### ISSUE TITLE
Stream Type

### ISSUE THREAD

**Issue by matthias-zivim** [DYefremov/DemonEditor#43]
There are different stream types. Are you going to support this? Found in e-channelizer

![image](https://user-images.githubusercontent.com/60196276/104121924-34941900-5342-11eb-9ef3-52dfd93b40dd.jpeg)

Thanks for the great work. I am using the Mac version.

**Comment by DYefremov** [comment]
Hi, this has already been implemented! It's just called differently. 
![stream_types_mac](https://user-images.githubusercontent.com/7511379/104122874-a8412080-5358-11eb-8754-17e01430b0e3.png)


Best

**Comment by DYefremov** [comment]
Hi. Added one more stream type. 
![stream_type](https://user-images.githubusercontent.com/7511379/104448524-572a6a00-55ae-11eb-935a-8342f26c7f57.png)

If you have any more questions or wishes, please let me know!

Best
