### ISSUE TITLE
AUR package available (Arch Linux)

### ISSUE THREAD

**Issue by vpont** [DYefremov/DemonEditor#44]
Hi Dmitriy,

FYI there's an AUR package already available for Arch Linux users, in case you want to add it to the README.md:
https://aur.archlinux.org/packages/demoneditor-bin

Regards.

**Comment by DYefremov** [comment]
Hi Víctor,
Thanks for the info.
I [added](https://github.com/DYefremov/DemonEditor/tree/development) with pleasure. If you have any comments, let me know. 

Best.

**Comment by vpont** [comment]
Looks good.
Keep up the good work!
