### ISSUE TITLE
Receiving Picons quits after getting links

### ISSUE THREAD

**Issue by tschmidt01** [DYefremov/DemonEditor#46]
Version: 1.0.6 Beta, Mac OS Build

After selecting a satellite and loading the providers, the "Receive picons" action quits after getting the links and thus does not download any images. I've tried it for different packages, but for none of them the picons get downloaded.

![Screenshot 2021-04-02 at 23 37 59](https://user-images.githubusercontent.com/15064827/113456064-82ce2b00-940c-11eb-9728-0fa1f04f358a.png)

**Comment by DYefremov** [comment]
Hello,
Please try [this](https://github.com/DYefremov/DemonEditor/releases/download/1.0.7-b1-macOS/DemonEditor.dmg) build. 
![picons_downloading](https://user-images.githubusercontent.com/7511379/113471056-8096bb80-9462-11eb-8cf5-0ca8970a0f2d.png)

**Comment by tschmidt01** [comment]
Works, thanks a lot!

**Comment by DYefremov** [comment]
Hello,
I added another small fix and updated the build. Let me know if something is wrong.
![providers_name](https://user-images.githubusercontent.com/7511379/113476898-0167ae80-9487-11eb-801d-8caf8e7572c9.png)

**Comment by tschmidt01** [comment]
There might be another problem with downloading the picons, when you select all providers the same thing happens as what I've opened the issue for (except is does not quit but gets stuck in "please wait"):

![Screenshot 2021-04-03 at 13 28 05](https://user-images.githubusercontent.com/15064827/113477227-b0ed5280-9480-11eb-8687-d8f9646ac4fd.png)

**Comment by DYefremov** [comment]
Yes you are right. There was an error loading picons for some single channels. Please [test it](https://github.com/DYefremov/DemonEditor/releases/download/1.0.7-b1-macOS/DemonEditor.dmg). Hopefully it's fixed now. :) 
Since LyngSat can change the page format and content at any time, it is possible to repeat this case.

**Comment by tschmidt01** [comment]
Works perfectly, will open a new issue if I find something :) Thanks a lot!

**Comment by DYefremov** [comment]
Thanks. I'll be glad to any comments and suggestions.
