### ISSUE TITLE
epg assign

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#51]
could you add epg assign to iptv channels from satelite channels list?
- add "service refrence" from satelite list to iptv channels list;
I thing some version before had that option, but not sure

**Comment by luxorko** [comment]
thank you for advice
would be nice if can be vissible:
- EPG Source (left side) satelite possition of channels 
- Bouquet Detail (right side) channels names (from epg source) see if auto assign pick correctly.
helpfull if you have long list of IPTV channels

**Comment by DYefremov** [comment]
Hi,
I added displaying the position and EPG source as a tooltip.

![epg](https://user-images.githubusercontent.com/7511379/139578737-4b1b766a-a259-445b-a92f-9ba24afd318b.png)

Adding a separate column for displaying the source seems to me to be superfluous for now. Although in the future we can think about it. :)

**Comment by luxorko** [comment]
thak you. waiting for new compilation, and give you feedback

**Comment by DYefremov** [comment]
We can close it for now.
