### ISSUE TITLE
import files

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#54]
current version not support add bouquet.tv and m3u files from folder on pc.
IPTV channels list created on the userbouquet.tv format 
i thing some versions before had that future.could you add again please with m3u 
at the moment we can transfering only whole list where lamedb is present

**Comment by DYefremov** [comment]
Hi,
It's not entirely clear what you mean. 
1. Single import of bouquets is available through the context menu of the bouquets list. 
2. Through the menu: File-> Import-> Bouquet.
3. Selective import of several bouquets through the menu :  File-> Import-> Bouquets ans services.

In addition, import is available via _drag and drop_. For bouquets, drag a single bouquet or folder onto the list of bouquets. For bouquet and services on the main list of services!  If you are using OS other than Linux, this function may not work correctly yet. Perhaps you mean this? 

> only whole list where lamedb is present

Just create a new configuration: File-> New empty configuration. Create a new bouquet and import _*.m3u_. Then, if necessary, you can export this bouquet through the context menu of the list of bouquets "Save As".  Or you meant something else?

Best

**Comment by luxorko** [comment]
1 - Drag and drop  - not working - 
2 - "File-> Import-> Bouque"... folder with userbouquet.tv not opening 
3 -" File-> New empty configuration. Create a new bouquet and import *.m3u" - 
this option (Create a new bouquet and import *.m3u - not exist-cannot find ( where could be?)

only can opening folder where is userbouquet. tv with lamedb

**Comment by DYefremov** [comment]
Apparently we still do not understand each other. :)

![new_configuration](https://user-images.githubusercontent.com/7511379/146436770-75e39fdb-bb64-42a0-820b-94473a489ca8.png)
![import_m3u](https://user-images.githubusercontent.com/7511379/146436805-f8fe4e89-232c-4bc6-88cb-e5df8493cacd.png)
![single_import](https://user-images.githubusercontent.com/7511379/146436818-7b19806d-32b3-4c70-99f7-b8a2cbdb6c6a.png)
or:
![single_import_2](https://user-images.githubusercontent.com/7511379/146436834-060d4ce5-d94f-4c9f-ae62-5c01cf31dd80.png)
![open](https://user-images.githubusercontent.com/7511379/146436957-27ee688c-b9c1-4d29-9f33-c4d288976e90.png)



> Drag and drop - not working -



> If you are using OS other than Linux, this function may not work correctly yet.

What operating system are you using (Windows, Linux, macOS)? 

I've tested imports on Linux and Windows 10. Everything works except drag and drop in Windows (BUT it is written about it above). 
Please describe in steps what you want to do. It might be easier to understand.

**Comment by luxorko** [comment]
![Capture](https://user-images.githubusercontent.com/65136999/146453601-b5a29729-a021-40e7-85f7-8d18b55d869d.JPG)
icon on the Demon are too small, my eyes are old.
could you make them bigger please?

find it bug:
1 - epty new configuration 
2 - import m3u files
3 - nothing happend (non choise for pick m3u files)
4 - first need load any bouquet and them you can load m3u files

rest working like charm. thank you pictures

**Comment by luxorko** [comment]
during downloading picons, VPN must be deactivated othervise download not start
it is normal?

**Comment by luxorko** [comment]
during downloading picons, VPN must be deactivated othervise download not start
it is normal?

**Comment by luxorko** [comment]
i think you could close it now. thank you

**Comment by luxorko** [comment]
one more thing. 
you got downloading one setup for Hispasat 30W and second from Eutelsat 36 B,C 
both satellite are impossible to scan by one satellite dish
how to joint both lamedb together? its possible?
think will be usefull for watching IPTV and get EPG
hope you know what i thing

**Comment by DYefremov** [comment]
> how to joint both lamedb together? its possible?

Yes, sure. Through the import function (File -> Import -> Bouquets and services). You can load one configuration then import the next one.  Or via drag and drop (In the current version may not work in Windows. ). For an example, see [here](https://www.youtube.com/watch?v=MybSevjQiN0).  I recommend watching the entire [playlist](https://www.youtube.com/playlist?list=PLB16nAGnuDczIx8NXyJYHuA9EPtDTRPHq). Many questions will probably disappear. 

> think will be usefull for watching IPTV and get EPG
Yes, it is planned, but I cannot say when it will be implemented yet.

**Comment by luxorko** [comment]
think you can close this thread. thank you for instruction how to use this fantastic plugin
