### ISSUE TITLE
satellite update problem 

### ISSUE THREAD

**Issue by i-mirror** [DYefremov/DemonEditor#55]
FlySat satellite update is not working.

**Comment by i-mirror** [comment]
thank's for your job.

**Comment by DYefremov** [comment]
Corrected. Didn't test it completely. There may be more changes.  In addition, the guys from FlySat can also make their own adjustments.  :)

**Comment by DYefremov** [comment]
FlySat started using Cloudflare. It may need to add support for [cloudscraper](https://pypi.org/project/cloudscraper/) lib.
