### ISSUE TITLE
Просьба добавить сохранение m3u целого букета спутниковых каналов из редактора

### ISSUE THREAD

**Issue by dikonov** [DYefremov/DemonEditor#56]
Многие ресиверы с Энигмой поддерживают раздачу спутниковых каналов с тарелки в виде IPTV (работают как личный сервер IPTV). Для использования функции нужно создать свой список ссылок на каналы в формате m3u. В старых версиях OpenATV это можно было сделать в веб-интерфейсе OpenWebIF, но теперь это не работает. Можно получать ссылки только для одного канала за раз, а потом вручную их склеивать в общий список. 

Просьба добавить в редактор функцию сохранения всего букета в виде m3u для удаленного просмотра IPTV со своего ресивера.
Ее можно поместить в меню действий с букетом, рядом с "Save As" или оформить как формат сохранения.

Вместе с тем, в меню правой конки мыши на каналах есть пункт IPTV/Export ro m3u, который не работает.Выдается дурацкая ошибка "Текущий список не содержит потоков IPTV". И что из этого следует? Ресивер сам умеет эти потоки создавать. Если есть IPTV каналы перемешанные с DVB, то они уже были импортированы из списка. Полезность функции извлечения обратно уже известных импортированных ссылок IPTV явно ниже чем получение сетевой ссылки на DVB канал.

**Comment by DYefremov** [comment]
> "Текущий список не содержит потоков IPTV".

Это было сделано специально для экспорта **только** IPTV списков. 

> Полезность функции извлечения обратно уже известных импортированных ссылок IPTV явно ниже чем получение сетевой ссылки на DVB канал.

Не поверите, но именно такое поведение также востребовано. Достаточно мало пользователей смешивают DVB и IPTV каналы. 

> Ее можно поместить в меню действий с букетом, рядом с "Save As"

Да, думаю можно сделать. Как вариант "Save As *m3u". Поэкспериментирую на досуге.

**Comment by DYefremov** [comment]
Добавил запрашиваемый функционал. Надеюсь, что будет действительно полезно.

![export](https://user-images.githubusercontent.com/7511379/147569381-2430caea-e7a8-4bdc-8af9-136adb69e435.png)
![export_bouquet](https://user-images.githubusercontent.com/7511379/147569391-bf77d2ac-326e-49e4-97fc-4d968e101565.png)

**Comment by dikonov** [comment]
Спасибо!
Сохранение в m3u позволяет смотреть свою тарелку там, где не работает редактор: на телефоне, планшете, телевизоре в другом городе и т.п. Так что это важная функция!
