### ISSUE TITLE
App force closes on macOS Monterey 12.1

### ISSUE THREAD

**Issue by jffluis** [DYefremov/DemonEditor#57]
As stated the app force closes on macOS Monterey 12.1.

**Comment by DYefremov** [comment]
Hello. Is [Homebrew](https://brew.sh/) installed on the system? There may be a library conflict. If so, try to temporarily remove all **GLib**-related packages. Alternatively, remove all packages completely, if possible.

 `brew remove --force $(brew list)`

**Comment by jffluis** [comment]
I will try it now. TY.
If have some updates i reach to you

**Comment by jffluis** [comment]
UPDATE: Updated brew and all fine now. Thank you.

**Comment by DYefremov** [comment]
I also ran a small test on a virtual machine.
 The problem, as I wrote, is in conflict with the **GLib** part (libgio). If you are Homebrew user, then you can run the program from source as on Linux. If not, and you are using a package from _*.dmg_, then Homebrew and something else do not need to be installed. Everything is already included in the package! 

Best
