### ISSUE TITLE
Multiple selection of services in Ubuntu [Shift + Up/Down]

### ISSUE THREAD

**Issue by i-mirror** [DYefremov/DemonEditor#61]
Cannot select multiple services with the keyboard.

**Comment by DYefremov** [comment]
Hi,
What OS and what combinations (Ctrl + A, Shift + Up / Down, using Space)? 
I can't reproduce on Linux. Everything works as it should! Having briefly tested on Windows and macOS (in a virtual machine), I can only confirm the selection using the **Space** key (as in the two panel file managers). But this feature, if I remember correctly, was not supported earlier in these OSes.

**Comment by DYefremov** [comment]
I tested also under Ubuntu 20.04.3 (in a VM) and also can't reproduce. Combination Shift + Up /Down Arrow is working. What hardware are you using. Laptop?

**Comment by i-mirror** [comment]
I use a pc with i7-2600k.
Shift + down / up selection only works with the bouquets name column.

**Comment by DYefremov** [comment]
This is quite interesting. You see the cursor change when you press Up and Down arrows in the main list?

![cursor](https://user-images.githubusercontent.com/7511379/151396158-74e4b8de-c0d4-4902-8527-15385ac51e4b.png)

I also made a small modification to log keystrokes. Please run from a terminal and press the Shift, Up and Down keys in sequence and show the output. 
![keys](https://user-images.githubusercontent.com/7511379/151396711-5d9e3944-ace7-47eb-8f7f-08f1ea60af77.png)


[DemonEditor.zip](https://github.com/DYefremov/DemonEditor/files/7951925/DemonEditor.zip)

**Comment by i-mirror** [comment]
This is what happens in the services column.

![Screenshot_20220127_183529](https://user-images.githubusercontent.com/7964751/151412917-e25ce1c0-fa77-49eb-9074-985e9ab467cb.png)


This is what happens in the bouquet name column. 

![Screenshot_20220127_183143](https://user-images.githubusercontent.com/7964751/151412525-1bb7b0a0-ee22-49be-abbc-2daae1a9d4eb.png)

**Comment by DYefremov** [comment]
Yes, it's Bug. Please test the [latest changes](https://github.com/DYefremov/DemonEditor/archive/refs/heads/development-2.0.zip).
