### ISSUE TITLE
Issue deletion picon

### ISSUE THREAD

**Issue by i-mirror** [DYefremov/DemonEditor#62]
In ubuntu unable to remove all unused picons.

![Screenshot_20220127_215018](https://user-images.githubusercontent.com/7964751/151441641-5addcf81-46c4-4b9a-a6db-d9ad94d643ff.png)

**Comment by DYefremov** [comment]
Yes. This feature has been broken in the latest version. Corrected. Please [test](https://github.com/DYefremov/DemonEditor/archive/refs/heads/development-2.0.zip). Thanks!

**Comment by i-mirror** [comment]
OK, now works.
