### ISSUE TITLE
File chooser dialog Gtk+ pattern filter error in macOS

### ISSUE THREAD

**Issue by ctlcltd** [DYefremov/DemonEditor#63]
There is an error with Gtk+ native file chooser dialog and macOS with file type filtering.

> userbouquet.*.tv is not a valid allowedFileType because it cannot be converted to a UTType

I don't know *UTType* but it could be fixed like this?

```python
#imports.py
        if IS_DARWIN:
            f_pattern = "*{}".format(pattern)
        else:
            f_pattern = "userbouquet.*{}".format(pattern)
```

Environment: macOS Monterey, Python 3.9, gtk+3 3.24.30-1

**Comment by DYefremov** [comment]
Сorrected!
