### ISSUE TITLE
Bouquet item disappers when re-ordering in treeview

### ISSUE THREAD

**Issue by ctlcltd** [DYefremov/DemonEditor#64]
When re-ordering a bouquet item in the tree view with DND, the item disappers. And it is not saved anymore.

Environment: macOS Monterey, Python 3.9, gtk+3 3.24.30-1

**Comment by DYefremov** [comment]
Hi,
Yes, it's a bug. And interesting. Need to figure it out.

**Comment by DYefremov** [comment]
Yes, I forgot to transfer from the old mac [branch](https://github.com/DYefremov/DemonEditor/tree/development-mac). :) Fixed.
