### ISSUE TITLE
New feature t2mi_plp_id

### ISSUE THREAD

**Issue by i-mirror** [DYefremov/DemonEditor#70]
Is it possible to add the parameter t2mi_plp_id in satellites?

![1](https://user-images.githubusercontent.com/7964751/157770580-dfbaac3c-e4bb-4e43-8f76-2b18e03ffaec.png)

**Comment by DYefremov** [comment]
I think yes.

**Comment by DYefremov** [comment]
Ready. Not tested! 

![t2-mi](https://user-images.githubusercontent.com/7511379/157832797-c31b1e4d-103c-419e-9d33-c9c0825fe3e5.png)

**Comment by i-mirror** [comment]
Tested and working, thanks.
