### ISSUE TITLE
Multiple bouquets

### ISSUE THREAD

**Issue by i-mirror** [DYefremov/DemonEditor#81]
It is possible to import multiple bouquets at the same time?

![0000](https://user-images.githubusercontent.com/7964751/159354899-c8883f18-5b47-4608-999d-e58448008eef.png)

**Comment by DYefremov** [comment]
Yes, sure.
![import](https://user-images.githubusercontent.com/7511379/159358404-a18a5aa0-dac8-44fb-9ab4-34c72d308072.png)

> When using the multiple import feature, from lamedb will be taken data only for channels that are in the selected bouquets!

**Comment by i-mirror** [comment]
I only want to import previously saved bouquets, without services.

**Comment by DYefremov** [comment]
If services are already in the main list, then nothing will be imported additionally. Just bouquets only.

**Comment by i-mirror** [comment]
OK, thanks.

**Comment by DYefremov** [comment]
Any time.
