### ISSUE TITLE
Translation doesn't matching

### ISSUE THREAD

**Issue by mapi68** [DYefremov/DemonEditor#85]
If you change language it remains in English but string are translated

![screenshot_2022_03_25_at_00_51_36](https://user-images.githubusercontent.com/41143572/160029745-fdc91ae1-5ca7-4011-9fe0-eebaea9b9648.png)
![screenshot_2022_03_25_at_01_07_26](https://user-images.githubusercontent.com/41143572/160029748-16e77048-bf4f-4b1c-bfab-fc2be90b4d22.png)

**Comment by DYefremov** [comment]
Yes, this is a known [issue](https://gitlab.gnome.org/GNOME/gtk/-/issues/569) and only affects Windows.  At the moment, this problem is solved by a workaround, but some nuances still remain.
