### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by mapi68** [DYefremov/DemonEditor#89]
When I try to download *.xml.gz I have CERTIFICATE_VERIFY_FAILED
For example with [this](https://i.mjh.nz/PlutoTV/it.xml.gz) link.

![screenshot_2022_04_02_at_11_05_44](https://user-images.githubusercontent.com/41143572/161376614-40aa56bb-d2c3-4925-88b4-ed9b7734c916.png)

**Comment by DYefremov** [comment]
Hi.
First, the file format at this link is not supported. Should be similar to [this](https://github.com/DYefremov/DemonEditor/issues/59#issuecomment-1019451085). 
Secondly. Very similar to [this](https://github.com/DYefremov/DemonEditor/issues/69) problem. For **standalone Windows** build only! Yes, there are solutions, but I need to think about how to do it more correctly.
