### ISSUE TITLE
IPTV List configuration

### ISSUE THREAD

**Issue by mapi68** [DYefremov/DemonEditor#90]
In Windows can edit values but after "Apply" DE doesn't really save

![screenshot_2022_04_04_at_08_55_34](https://user-images.githubusercontent.com/41143572/161489606-4189e7bd-01f0-4263-97ec-e7d31f478d34.png)

**Comment by DYefremov** [comment]
> doesn't really save

All changes in the lists of bouquets and services are stored in memory. You can check the changes. After clicking on "Apply" it is enough to try to edit one of the list services. To save the changes to disk, you need to click the "Save" button on the toolbar, through the "File" menu or Ctrl + S.

**Comment by mapi68** [comment]
Everything ok, thanks|
