### ISSUE TITLE
Are you sure? OK/Cancel in Windows and Linux

### ISSUE THREAD

**Issue by mapi68** [DYefremov/DemonEditor#91]
Tried version 2.2.3 with Raspberry Pi (debian) and it's AWESOME, but there is a difference in Win and Linux: default delection in Win is OK (left) an in Linux is Cancel (always on left). I think that the right way is Windows because you can confirm direct with keyboard ENTER

WIndows
![screenshot_2022_04_13_at_08_23_32](https://user-images.githubusercontent.com/41143572/163114767-1a9d0a8a-a467-40eb-8cfd-abc3ec787a89.png)

Linux
![2022-04-13-081851_1920x1080_scrot](https://user-images.githubusercontent.com/41143572/163114835-a436f308-962e-436a-b3d7-04f5ac471e09.png)

**Comment by DYefremov** [comment]
This location depends on the Gtk settings, OS and used desktop environment. This can be changed, but I see no reason to do so.

**Comment by DYefremov** [comment]
> No lose time to search OK with mouse and do click (simply ENTER in keyboard).

This is the **default** behavior! I also think this is the correct behavior. I think that a significant part of Linux users think the same.

> Or maybe add something like this:

I'm not sure if it's necessary, but I'll think about it.
