### ISSUE TITLE
Missing string translation in youtube-dl

### ISSUE THREAD

**Issue by mapi68** [DYefremov/DemonEditor#97]
Hi,
missing string translation in youtube-dl

![screenshot_2022_04_26_at_09_12_34](https://user-images.githubusercontent.com/41143572/165243582-65d1bb0e-6a82-41a0-9938-c4c6da0f6308.png)

**Comment by DYefremov** [comment]
Hi. Added with minor adjustments. Also changed "Record:" to "Recordings:" in the path tab.:)
